'use client'

import Image from 'next/image'
import { useState, type KeyboardEvent } from 'react'
import { MessageCircle, Mic, Check, ArrowUpRight, Clock3, ShieldCheck, Smartphone, Monitor, CheckCircle2, SlidersHorizontal, Sparkles, Headphones, Plus, Minus, Utensils, HeartHandshake } from 'lucide-react'
import { SiteNav } from '@/components/site-nav'
import { SiteFooter } from '@/components/site-footer'
import { LocalizedLink as Link } from '@/components/LocalizedLink'
import { useLang } from '@/lib/i18n/LanguageContext'
import './home-clarity.css'

const copy = {
  en: {
    skip: 'Skip to content', eyebrow: 'Great stays. Smarter revenue.', title: 'AI guest service.', titleAccent: 'More hotel revenue.',
    intro: 'Answer guest questions, recommend your hotel’s services, and send requests to the right team — through voice and chat.',
    primary: 'See it in action', secondary: 'Explore the pilot', channel: 'On your guests’ phones. Under your hotel’s name.',
    imageAlt: 'A quiet coastal hotel with a pool, stone arches and ocean views', yourHotel: 'Your hotel. Your brand.', guestCompanion: 'Guest companion', illustration: 'Illustrative conversation',
    heroQuestion: 'Our flight is at six. Could we stay a little longer?', heroAnswer: 'Late checkout until 2 pm is $45, subject to availability. Would you like me to send a request?', heroOffer: 'Late checkout', heroOfferDetail: 'Stay until 2 pm', heroStatus: 'Hotel confirmation required', price: '$45',
    outcomes: [
      { title: 'Answer routine questions', body: 'Give guests your hotel’s approved information, any time.' },
      { title: 'Offer relevant extras', body: 'Introduce dining, spa, upgrades and other hotel services.' },
      { title: 'Help your team follow through', body: 'Keep guest requests and next steps together.' },
    ],
    demoEyebrow: 'See how it works', demoTitle: 'One question. A useful next step.', demoIntro: 'Choose a guest moment. See the conversation and what your hotel receives.', demoLabel: 'Interactive walkthrough · Sample data · No live transactions', guestView: 'What your guest sees', staffView: 'What your team receives', room: 'Room 214', guest: 'Guest', companion: 'Hotel Companion', next: 'Show the next step', restart: 'Replay this example', stage: 'Step', of: 'of', context: 'Guest context', action: 'Next action', owner: 'Responsible team', status: 'Status',
    scenarios: [
      { tab: 'A service request', tag: 'Guest service', question: 'Could we have two more towels?', answer: 'Of course. I’ll send your request to housekeeping for room 214.', reply: 'Thank you. We’re heading to the pool.', follow: 'Your request has been sent. The hotel team will confirm the next step.', staffTitle: 'Two extra towels', context: 'Room 214 · Guest is heading to the pool', owner: 'Housekeeping', action: 'Acknowledge the request and arrange delivery.', steps: ['Request captured', 'Sent to housekeeping', 'Awaiting staff confirmation'], benefit: 'Your guest gets a clear answer. Your team gets the details it needs.' },
      { tab: 'A relevant offer', tag: 'Hotel revenue', question: 'We’re celebrating our anniversary. Any dinner ideas?', answer: 'The terrace dinner could be a lovely fit. The hotel’s menu is $120 for two. Would you like me to ask about a table?', reply: 'Yes, please. Around 8 pm.', follow: 'I’ve sent your request for two at 8 pm. The restaurant will confirm availability.', staffTitle: 'Anniversary dinner request', context: 'Room 214 · Two guests · 8 pm preferred', owner: 'Restaurant', action: 'Check availability and confirm the table with the guest.', steps: ['Relevant option offered', 'Guest interest captured', 'Awaiting restaurant confirmation'], benefit: 'A guest-stated occasion becomes a relevant, hotel-approved offer.' },
      { tab: 'A problem to solve', tag: 'Human support', question: 'The air conditioning isn’t working and we can’t sleep.', answer: 'I’m sorry. I’ll pass this to the hotel team with your room details so they can help.', reply: 'Please ask someone to call us.', follow: 'Your request includes a call back. The hotel team needs to confirm who can help and when.', staffTitle: 'Air conditioning · Call back requested', context: 'Room 214 · Guest cannot sleep', owner: 'Front desk / Engineering', action: 'Contact the guest, assess the problem and take ownership.', steps: ['Issue captured', 'Human help requested', 'Awaiting team response'], benefit: 'Service comes first. Sales offers are paused while a problem is unresolved.' },
    ],
    revenueEyebrow: 'More from the services you already offer', revenueTitle: 'Make the right offer easier to say yes to.', revenueIntro: 'Give guests a useful reason to spend with your hotel. Keep the price, benefit and cost under your control.',
    recTitle: 'Recommendations that fit the moment', recBody: 'Use what a guest actually tells you — their plans, interests and timing — to suggest relevant services.', recNote: 'An anniversary dinner for a celebrating couple. A late-checkout request for a late flight. No offer when the guest needs help.',
    recExample: 'Guest says', recQuote: '“We’re celebrating our anniversary.”', recResult: 'Suggest the terrace dinner for two',
    dealTitle: 'Packages with a clear reason to buy', dealBody: 'Combine approved services with a benefit guests value. Check the economics before the offer is approved.', dealExample: 'Illustrative hotel-approved package', dinner: 'Dinner for two', spa: 'Two spa treatments', package: 'Package price', benefitLabel: 'Included benefit', benefitValue: '$25 dining credit', dealNote: 'Eligibility, delivery costs and the cost of the benefit are reviewed by the hotel. Requests need confirmation.',
    controlsEyebrow: 'Companion Control', controlsTitle: 'Your prices. Your rules. Your team in control.', controlsIntro: 'Approve the information and offers guests receive. Give staff a clear view of requests that need attention.', controls: [ ['Approve every offer', 'Set prices, costs, eligibility and included benefits.'], ['Keep people in the loop', 'Your team confirms requests and handles exceptions.'], ['Separate interest from revenue', 'Measure fulfilled, settled sales against the agreed pilot comparison.'] ],
    panelTitle: 'Offer review', panelMeta: 'Sample hotel · Illustrative values', panelName: 'Dinner + spa package', panelRows: [['Package price', '$260'], ['Estimated service costs', '−$100'], ['Benefit allowance', '−$20']], contribution: 'Estimated contribution', contributionValue: '$140', contributionNote: 'Before HC fees and other agreed costs. An estimate, not a measured result.', ruleTitle: 'Before a guest sees this offer', rules: ['Hotel review required', 'Eligible guests only', 'Availability confirmed by staff'],
    setupEyebrow: 'A focused start', setupTitle: 'Start with one hotel. One clear use case.', setupIntro: 'We agree the scope with your team before launch. Guests use a link or QR code on the devices they already have.', setupSteps: [ ['Choose the opportunity', 'Pick one guest journey and agree what a successful pilot will measure.'], ['Approve your content', 'Review hotel information, offers, staff responsibilities and any required connections.'], ['Test, launch and review', 'Run guest scenarios, launch the agreed scope and review results together.'] ],
    channels: 'Ways guests can reach you', mobile: 'Mobile web', desktop: 'Desktop web', voice: 'Voice & chat', channelNote: 'Telephone and WhatsApp connections are scoped separately. In-room tablets offer a dedicated guest experience, with hardware and installation tailored to your property.',
    pilotEyebrow: 'The outcome-based pilot', pilotTitle: 'Prove the value at your hotel.', pilotIntro: 'For qualified hotels, start with no upfront software or standard setup fee. HC earns an agreed share of verified additional contribution.', pilotSub: 'The measurement, costs and payment terms are agreed before launch.', pilotCta: 'Discuss a pilot for my hotel', pilotMini: 'One property first. Expand when the results justify it.',
    pilotRows: [['You provide', 'An engaged hotel team, approved information and access to the records needed to measure results.'], ['We agree together', 'One use case, a comparison method, eligible sales, costs, success fee and pilot duration.'], ['You pay for', 'Verified additional contribution under the agreed terms. No verified lift, no success fee.']], pilotMore: 'How results and expansion are handled', pilotDetails: 'We distinguish sales assisted by HC from genuinely additional contribution. Fulfillment, cancellations, refunds, delivery costs and any benefits are accounted for under the agreed method. Custom integrations and optional hardware are scoped separately. A wider rollout is a separate decision, with implementation costs agreed before expansion.',
    faqTitle: 'A few practical questions.', faqs: [
      ['Do guests need to download an app?', 'No. Guests can open the companion through a link or QR code in a mobile or desktop browser and use voice or chat.'],
      ['Does HC replace our front-desk team?', 'HC handles routine questions and organizes guest requests. Your staff remain responsible for confirmations, physical service and situations that need human judgment.'],
      ['Will it connect to our hotel systems?', 'We review your systems and the chosen workflow before agreeing the pilot. Live availability, reservation changes and payments are included only where the required connection has been verified for your property.'],
      ['What makes the recommendations relevant?', 'Guest-stated interests, hotel-approved eligibility rules, prices and costs guide the offer. The system can choose not to offer anything. Room category alone should never decide what a guest can enjoy.'],
      ['How will we know whether it made money?', 'Before launch, we agree which outcomes count and how to compare them with what would have happened without HC. We review fulfilled and settled transactions, not simply the value of requests sent.'],
    ], footerCta: 'Let’s find the right first use case for your hotel.', footerButton: 'Request a demo',
  },
  es: {
    skip: 'Saltar al contenido', eyebrow: 'Grandes estancias. Mejores ingresos.', title: 'Mejor atención.', titleAccent: 'Más ingresos.',
    intro: 'Hotel Companion responde preguntas, recomienda los servicios de tu hotel y envía solicitudes al equipo indicado — por voz y chat.', primary: 'Mira cómo funciona', secondary: 'Conoce el piloto', channel: 'En el teléfono de tus huéspedes. Con la marca de tu hotel.',
    imageAlt: 'Un hotel junto al mar con alberca, arcos de piedra y vistas al océano', yourHotel: 'Tu hotel. Tu marca.', guestCompanion: 'Asistente del huésped', illustration: 'Conversación ilustrativa', heroQuestion: 'Nuestro vuelo sale a las seis. ¿Podemos quedarnos un poco más?', heroAnswer: 'La salida hasta las 2 pm cuesta $45, sujeta a disponibilidad. ¿Quieres que envíe una solicitud?', heroOffer: 'Salida tardía', heroOfferDetail: 'Quédate hasta las 2 pm', heroStatus: 'Requiere confirmación del hotel', price: '$45',
    outcomes: [ { title: 'Responde preguntas frecuentes', body: 'Comparte la información aprobada de tu hotel a cualquier hora.' }, { title: 'Ofrece servicios relevantes', body: 'Presenta opciones de restaurante, spa, mejoras y otros servicios.' }, { title: 'Ayuda al equipo a dar seguimiento', body: 'Mantén juntas las solicitudes y sus próximos pasos.' } ],
    demoEyebrow: 'Así funciona', demoTitle: 'Una pregunta. Un siguiente paso claro.', demoIntro: 'Elige un momento de la estancia. Mira la conversación y lo que recibe el hotel.', demoLabel: 'Recorrido interactivo · Datos de ejemplo · Sin transacciones reales', guestView: 'Lo que ve el huésped', staffView: 'Lo que recibe tu equipo', room: 'Habitación 214', guest: 'Huésped', companion: 'Hotel Companion', next: 'Ver el siguiente paso', restart: 'Repetir este ejemplo', stage: 'Paso', of: 'de', context: 'Contexto del huésped', action: 'Siguiente acción', owner: 'Equipo responsable', status: 'Estado',
    scenarios: [
      { tab: 'Una solicitud', tag: 'Atención al huésped', question: '¿Nos pueden traer dos toallas más?', answer: 'Claro. Enviaré la solicitud a ama de llaves para la habitación 214.', reply: 'Gracias. Vamos a la alberca.', follow: 'La solicitud fue enviada. El equipo del hotel confirmará el siguiente paso.', staffTitle: 'Dos toallas adicionales', context: 'Habitación 214 · El huésped va a la alberca', owner: 'Ama de llaves', action: 'Confirmar la recepción y coordinar la entrega.', steps: ['Solicitud registrada', 'Enviada a ama de llaves', 'Pendiente de confirmación'], benefit: 'El huésped recibe una respuesta clara. Tu equipo recibe los detalles necesarios.' },
      { tab: 'Una oferta relevante', tag: 'Ingresos del hotel', question: 'Celebramos nuestro aniversario. ¿Alguna idea para cenar?', answer: 'La cena en la terraza puede ser ideal. El menú del hotel cuesta $120 para dos. ¿Quieres que pregunte por una mesa?', reply: 'Sí, por favor. Alrededor de las 8 pm.', follow: 'Envié tu solicitud para dos a las 8 pm. El restaurante confirmará la disponibilidad.', staffTitle: 'Solicitud de cena de aniversario', context: 'Habitación 214 · Dos personas · Preferencia: 8 pm', owner: 'Restaurante', action: 'Revisar disponibilidad y confirmar la mesa con el huésped.', steps: ['Opción relevante presentada', 'Interés del huésped registrado', 'Pendiente de confirmación'], benefit: 'Una ocasión mencionada por el huésped se convierte en una oferta relevante y aprobada.' },
      { tab: 'Un problema', tag: 'Apoyo humano', question: 'El aire acondicionado no funciona y no podemos dormir.', answer: 'Lo siento. Avisaré al equipo del hotel con los datos de tu habitación para que pueda ayudarte.', reply: 'Por favor, que alguien nos llame.', follow: 'Tu solicitud incluye una llamada. El hotel debe confirmar quién puede ayudar y cuándo.', staffTitle: 'Aire acondicionado · Solicita llamada', context: 'Habitación 214 · El huésped no puede dormir', owner: 'Recepción / Mantenimiento', action: 'Contactar al huésped, evaluar el problema y hacerse responsable.', steps: ['Problema registrado', 'Ayuda humana solicitada', 'Pendiente de respuesta'], benefit: 'El servicio es primero. Las ofertas se pausan mientras exista un problema sin resolver.' },
    ],
    revenueEyebrow: 'Más de los servicios que ya ofreces', revenueTitle: 'Haz que la oferta adecuada sea fácil de aceptar.', revenueIntro: 'Dale al huésped una buena razón para consumir en tu hotel. Mantén el control del precio, el beneficio y el costo.', recTitle: 'Recomendaciones para cada momento', recBody: 'Usa lo que el huésped te dice —sus planes, intereses y horarios— para sugerir servicios relevantes.', recNote: 'Una cena de aniversario. Una salida tardía para un vuelo por la tarde. Ninguna oferta cuando necesita ayuda.', recExample: 'El huésped dice', recQuote: '“Estamos celebrando nuestro aniversario.”', recResult: 'Sugerir una cena en la terraza para dos', dealTitle: 'Paquetes con una razón clara para comprar', dealBody: 'Combina servicios aprobados con un beneficio que valore el huésped. Revisa los costos antes de aprobar la oferta.', dealExample: 'Ejemplo de paquete aprobado por el hotel', dinner: 'Cena para dos', spa: 'Dos tratamientos de spa', package: 'Precio del paquete', benefitLabel: 'Beneficio incluido', benefitValue: '$25 de crédito en restaurante', dealNote: 'El hotel revisa la elegibilidad, los costos de los servicios y del beneficio. Las solicitudes requieren confirmación.',
    controlsEyebrow: 'Companion Control', controlsTitle: 'Tus precios. Tus reglas. Tu equipo al mando.', controlsIntro: 'Aprueba la información y las ofertas que reciben los huéspedes. Dale a tu equipo una vista clara de las solicitudes pendientes.', controls: [['Aprueba cada oferta', 'Define precios, costos, elegibilidad y beneficios incluidos.'], ['Mantén a tu equipo involucrado', 'El hotel confirma solicitudes y atiende las excepciones.'], ['Distingue interés de ingresos', 'Compara ventas realizadas y cobradas con la referencia acordada para el piloto.']], panelTitle: 'Revisión de oferta', panelMeta: 'Hotel de ejemplo · Valores ilustrativos', panelName: 'Paquete de cena + spa', panelRows: [['Precio del paquete', '$260'], ['Costos estimados de los servicios', '−$100'], ['Costo presupuestado del beneficio', '−$20']], contribution: 'Contribución estimada', contributionValue: '$140', contributionNote: 'Antes de honorarios de HC y otros costos acordados. Es una estimación, no un resultado medido.', ruleTitle: 'Antes de que el huésped vea la oferta', rules: ['Revisión del hotel requerida', 'Solo huéspedes elegibles', 'Disponibilidad confirmada por el equipo'],
    setupEyebrow: 'Un inicio enfocado', setupTitle: 'Empieza con un hotel. Un caso de uso claro.', setupIntro: 'Acordamos el alcance con tu equipo antes del lanzamiento. Los huéspedes usan un enlace o QR en los dispositivos que ya tienen.', setupSteps: [['Elige la oportunidad', 'Selecciona una experiencia y acuerda cómo medir el éxito del piloto.'], ['Aprueba tu contenido', 'Revisa información, ofertas, responsables y las conexiones necesarias.'], ['Prueba, lanza y revisa', 'Valida los escenarios, lanza el alcance acordado y revisa los resultados con nosotros.']], channels: 'Cómo pueden contactarte tus huéspedes', mobile: 'Web móvil', desktop: 'Web de escritorio', voice: 'Voz y chat', channelNote: 'Las conexiones de teléfono y WhatsApp se definen por separado. Las tablets en la habitación ofrecen una experiencia dedicada, con dispositivos e instalación adaptados a tu hotel.',
    pilotEyebrow: 'El piloto basado en resultados', pilotTitle: 'Demuestra el valor en tu hotel.', pilotIntro: 'Los hoteles elegibles pueden empezar sin pago inicial de software ni configuración estándar. HC recibe una participación acordada de la contribución adicional verificada.', pilotSub: 'La medición, los costos y las condiciones de pago se acuerdan antes del lanzamiento.', pilotCta: 'Hablar del piloto para mi hotel', pilotMini: 'Primero una propiedad. Amplía cuando los resultados lo justifiquen.', pilotRows: [['Tu hotel aporta', 'Un equipo comprometido, información aprobada y acceso a los registros necesarios para medir resultados.'], ['Acordamos juntos', 'Un caso de uso, método de comparación, ventas elegibles, costos, honorarios y duración.'], ['Pagas por', 'Contribución adicional verificada bajo las condiciones acordadas. Sin mejora verificada, no hay honorario por éxito.']], pilotMore: 'Cómo se manejan los resultados y la expansión', pilotDetails: 'Distinguimos las ventas asistidas por HC de la contribución realmente adicional. El método acordado contempla servicios realizados, cancelaciones, reembolsos, costos y beneficios. Las integraciones especiales y los equipos opcionales se cotizan por separado. La expansión se decide después, con costos de implementación acordados previamente.',
    faqTitle: 'Respuestas prácticas.', faqs: [['¿El huésped necesita descargar una app?', 'No. Puede abrir el asistente desde un enlace o QR en un navegador móvil o de escritorio y usar voz o chat.'], ['¿HC reemplaza a recepción?', 'HC responde preguntas frecuentes y organiza solicitudes. Tu equipo sigue a cargo de las confirmaciones, la atención presencial y las situaciones que necesitan criterio humano.'], ['¿Se conecta a nuestros sistemas?', 'Revisamos tus sistemas y el caso de uso antes de acordar el piloto. La disponibilidad en tiempo real, los cambios de reserva y los pagos se incluyen solo con una conexión verificada para tu hotel.'], ['¿Cómo elige las recomendaciones?', 'Los intereses expresados por el huésped, las reglas de elegibilidad, los precios y los costos aprobados orientan la oferta. Puede decidir no ofrecer nada. La categoría de habitación por sí sola no debe determinar qué puede disfrutar un huésped.'], ['¿Cómo sabremos si generó ingresos?', 'Antes del lanzamiento acordamos qué resultados cuentan y cómo compararlos con lo que habría ocurrido sin HC. Revisamos transacciones realizadas y cobradas, no solo el valor de las solicitudes.']], footerCta: 'Encontremos el primer caso de uso para tu hotel.', footerButton: 'Solicitar una demo',
  },
}

export default function HomeClarityClient() {
  const { lang } = useLang()
  const c = copy[lang]
  const [scenario, setScenario] = useState(1)
  const [step, setStep] = useState(0)
  const s = c.scenarios[scenario]
  function choose(i:number) { setScenario(i); setStep(0) }
  function tabKey(e:KeyboardEvent<HTMLButtonElement>, i:number) {
    const next = e.key === 'ArrowRight' ? (i+1)%3 : e.key === 'ArrowLeft' ? (i+2)%3 : e.key === 'Home' ? 0 : e.key === 'End' ? 2 : null
    if(next !== null) { e.preventDefault(); choose(next); document.getElementById(`moment-tab-${next}`)?.focus() }
  }
  return <div className="hc-clear">
    <a className="clear-skip" href="#main">{c.skip}</a>
    <SiteNav appearance="light" />
    <main id="main">
      <section className="clear-hero clear-container" aria-labelledby="hero-title">
        <div className="clear-hero-copy">
          <p className="clear-kicker"><span />{c.eyebrow}</p>
          <h1 id="hero-title">{c.title}<br/><span>{c.titleAccent}</span></h1>
          <p className="clear-intro">{c.intro}</p>
          <div className="clear-actions"><a className="clear-btn" href="#how-it-works">{c.primary}<span className="clear-play" aria-hidden="true">▶</span></a><a className="clear-text-link" href="#pilot">{c.secondary}<ArrowUpRight size={17} aria-hidden="true" /></a></div>
          <p className="clear-channel"><Smartphone size={17} aria-hidden="true"/>{c.channel}</p>
        </div>
        <div className="clear-hero-visual">
          <Image src="/assets/editorial/hc-caribbean-arrival.webp" fill priority sizes="(max-width: 800px) 100vw, 48vw" alt={c.imageAlt} className="clear-hero-image" />
          <span className="clear-photo-label">{c.yourHotel}</span>
          <div className="clear-guest-card">
            <div className="clear-guest-brand"><span className="clear-brand-icon"><Sparkles size={18}/></span><div><strong>{c.guestCompanion}</strong><small>{c.illustration}</small></div><Mic size={18} aria-hidden="true" /></div>
            <p className="clear-chat-bubble">{c.heroQuestion}</p>
            <p className="clear-chat-reply">{c.heroAnswer}</p>
            <div className="clear-mini-offer"><span className="clear-mini-icon"><Clock3 size={22}/></span><div><strong>{c.heroOffer}</strong><span>{c.heroOfferDetail}</span></div><strong>{c.price}</strong></div>
            <div className="clear-pending"><Clock3 size={14} aria-hidden="true"/>{c.heroStatus}</div>
          </div>
        </div>
      </section>
      <div className="clear-outcomes clear-container">{c.outcomes.map((o,i)=>{const Icon=[MessageCircle,Sparkles,HeartHandshake][i];return <div className="clear-outcome" key={o.title}><Icon size={23} strokeWidth={1.6} aria-hidden="true"/><div><h2>{o.title}</h2><p>{o.body}</p></div></div>})}</div>
      <section className="clear-section clear-demo" id="how-it-works" aria-labelledby="demo-title">
        <div className="clear-container">
          <div className="clear-section-head"><p className="clear-kicker">{c.demoEyebrow}</p><h2 id="demo-title">{c.demoTitle}</h2><p>{c.demoIntro}</p></div>
          <div className="clear-tabs" role="tablist" aria-label={c.demoEyebrow}>{c.scenarios.map((m,i)=><button key={m.tab} id={`moment-tab-${i}`} role="tab" aria-selected={scenario===i} aria-controls="moment-panel" tabIndex={scenario===i?0:-1} onKeyDown={e=>tabKey(e,i)} onClick={()=>choose(i)}><span>0{i+1}</span>{m.tab}</button>)}</div>
          <div className="clear-demo-panel" id="moment-panel" role="tabpanel" aria-labelledby={`moment-tab-${scenario}`} tabIndex={0}>
            <div className="clear-demo-guest">
              <div className="clear-demo-label"><Smartphone size={17}/>{c.guestView}<span>{c.room}</span></div>
              <div className="clear-demo-messages"><p className="clear-message clear-message-guest">{s.question}</p><div className="clear-message-assistant"><span className="clear-brand-icon"><Sparkles size={16}/></span><p>{s.answer}</p></div>{step>0&&<p className="clear-message clear-message-guest clear-enter">{s.reply}</p>}{step>1&&<div className="clear-message-assistant clear-enter"><span className="clear-brand-icon"><Check size={16}/></span><p>{s.follow}</p></div>}</div>
              <div className="clear-demo-progress"><span>{c.stage} {step+1} {c.of} 3</span><button onClick={()=>setStep((step+1)%3)}>{step===2?c.restart:c.next}<ArrowUpRight size={16}/></button></div>
            </div>
            <div className="clear-demo-staff"><div className="clear-demo-label"><Monitor size={17}/>{c.staffView}<span>Companion Control</span></div><div className="clear-staff-ticket"><span className="clear-ticket-tag">{s.tag}</span><h3>{s.staffTitle}</h3><dl><div><dt>{c.context}</dt><dd>{s.context}</dd></div><div><dt>{c.owner}</dt><dd>{s.owner}</dd></div><div><dt>{c.action}</dt><dd>{s.action}</dd></div></dl><div className="clear-stages" aria-live="polite">{s.steps.map((label,i)=><div key={label} className={i<=step?'is-active':''}>{i<step?<CheckCircle2 size={16}/>:<span className="clear-stage-circle"/>}<span>{label}</span></div>)}</div></div></div>
          </div>
          <div className="clear-demo-caption"><p><Check size={17} aria-hidden="true"/>{s.benefit}</p><span>{c.demoLabel}</span></div>
        </div>
      </section>
      <section className="clear-section clear-revenue clear-container" id="revenue" aria-labelledby="revenue-title">
        <div className="clear-section-head"><p className="clear-kicker">{c.revenueEyebrow}</p><h2 id="revenue-title">{c.revenueTitle}</h2><p>{c.revenueIntro}</p></div>
        <div className="clear-revenue-grid"><article className="clear-recommendation"><div className="clear-revenue-photo"><Image src="/assets/ui/dish-1.webp" fill sizes="(max-width: 800px) 100vw, 45vw" alt={lang==='es'?'Una cena preparada por el restaurante del hotel':'A plated dinner from the hotel restaurant'}/><span><Utensils size={16}/>{lang==='es'?'RESTAURANTE':'DINING'}</span></div><div className="clear-revenue-content"><span className="clear-number">01 / {lang==='es'?'RECOMENDAR':'RECOMMEND'}</span><h3>{c.recTitle}</h3><p>{c.recBody}</p><div className="clear-recommendation-example"><small>{c.recExample}</small><blockquote>{c.recQuote}</blockquote><div><Sparkles size={16}/>{c.recResult}</div></div><p className="clear-small">{c.recNote}</p></div></article>
          <article className="clear-deal"><div className="clear-revenue-content"><span className="clear-number">02 / {lang==='es'?'COMBINAR':'PACKAGE'}</span><h3>{c.dealTitle}</h3><p>{c.dealBody}</p></div><div className="clear-package"><p>{c.dealExample}</p><div className="clear-package-item"><Utensils size={20}/><span>{c.dinner}</span></div><div className="clear-package-plus"><Plus size={15}/></div><div className="clear-package-item"><Sparkles size={20}/><span>{c.spa}</span></div><div className="clear-package-total"><span>{c.package}</span><strong>$260</strong></div><div className="clear-package-benefit"><span>{c.benefitLabel}</span><strong>{c.benefitValue}</strong></div></div><p className="clear-small clear-deal-note">{c.dealNote}</p></article></div>
      </section>
      <section className="clear-control" aria-labelledby="control-title"><div className="clear-container clear-control-grid"><div><p className="clear-kicker">{c.controlsEyebrow}</p><h2 id="control-title">{c.controlsTitle}</h2><p className="clear-control-intro">{c.controlsIntro}</p><div className="clear-control-points">{c.controls.map(([title,body],i)=>{const Icon=[SlidersHorizontal,Headphones,ShieldCheck][i];return <div key={title}><Icon size={21} aria-hidden="true"/><div><h3>{title}</h3><p>{body}</p></div></div>})}</div></div><div className="clear-review-panel"><div className="clear-review-bar"><SlidersHorizontal size={18}/><strong>{c.panelTitle}</strong><span>{lang==='es'?'BORRADOR':'DRAFT'}</span></div><div className="clear-review-content"><p className="clear-small">{c.panelMeta}</p><h3>{c.panelName}</h3><dl>{c.panelRows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}<div className="clear-contribution"><dt>{c.contribution}</dt><dd>{c.contributionValue}</dd></div></dl><p className="clear-small">{c.contributionNote}</p><div className="clear-review-rules"><strong>{c.ruleTitle}</strong>{c.rules.map(rule=><span key={rule}><Check size={15}/>{rule}</span>)}</div></div></div></div></section>
      <section className="clear-section clear-setup clear-container" id="setup" aria-labelledby="setup-title"><div className="clear-section-head"><p className="clear-kicker">{c.setupEyebrow}</p><h2 id="setup-title">{c.setupTitle}</h2><p>{c.setupIntro}</p></div><div className="clear-setup-steps">{c.setupSteps.map(([title,body],i)=><div key={title}><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></div>)}</div><div className="clear-channel-box"><div><p>{c.channels}</p><div className="clear-channel-list"><span><Smartphone size={20}/>{c.mobile}</span><span><Monitor size={20}/>{c.desktop}</span><span><Mic size={20}/>{c.voice}</span></div></div><p>{c.channelNote}</p></div></section>
      <section className="clear-pilot" id="pilot" aria-labelledby="pilot-title"><div className="clear-container clear-pilot-grid"><div><p className="clear-kicker">{c.pilotEyebrow}</p><h2 id="pilot-title">{c.pilotTitle}</h2><p className="clear-pilot-intro">{c.pilotIntro}</p><p>{c.pilotSub}</p><Link className="clear-btn" href="/demo">{c.pilotCta}<ArrowUpRight size={17}/></Link><small>{c.pilotMini}</small></div><div className="clear-pilot-terms">{c.pilotRows.map(([title,body],i)=><div key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></div>)}<details><summary>{c.pilotMore}<Plus size={17}/></summary><p>{c.pilotDetails}</p></details></div></div></section>
      <section className="clear-section clear-faq clear-container" id="questions"><div><p className="clear-kicker">{lang==='es'?'Antes de empezar':'Before you begin'}</p><h2>{c.faqTitle}</h2></div><div>{c.faqs.map(([q,a])=><details key={q}><summary>{q}<Plus className="clear-faq-plus" size={19}/><Minus className="clear-faq-minus" size={19}/></summary><p>{a}</p></details>)}</div></section>
      <div className="clear-bottom-cta clear-container"><p>{c.footerCta}</p><Link className="clear-btn" href="/demo">{c.footerButton}<ArrowUpRight size={17}/></Link></div>
    </main><SiteFooter/>
  </div>
}
