'use client'

import Image from 'next/image'
import { type ReactNode } from 'react'
import { ArrowRight, ShieldCheck, RotateCcw } from 'lucide-react'
import { SiteNav } from '@/components/site-nav'
import { SiteFooter } from '@/components/site-footer'
import { LocalizedLink as Link } from '@/components/LocalizedLink'
import { SalesDemoShowcase } from './SalesDemoShowcase'
import { ControlDashboard, VoiceSample, useWords } from './Experience'
import { HandoffDetails, PortfolioPreview, ServiceJourney } from './ServiceJourney'
import { FocusedPilot, HotelConnections, OnboardingTimeline } from './HomeClarity'
import { DemandInsight } from './DemandInsight'
import { Chapter, ChannelStage, ContributionExample, Details, MemoryPanel, PageIntro, PhotoStory, PilotTerms, RecoveryStory } from './PageSections'
import './inner-clarity.css'

export type ExperiencePageKey='platform'|'solutions'|'revenue'|'enterprise'|'implementation'|'company'|'contact'
export function ExperienceFrame({children}:{children:ReactNode}) {
 const t=useWords()
 return <div className="xp-site hc-inner"><a className="xp-skip" href="#main-content">{t('Skip to content','Saltar al contenido')}</a><SiteNav/><main id="main-content">{children}</main><SiteFooter/></div>
}

function Platform() {
 const t=useWords()
 return <><PageIntro eyebrow={t('THE PRODUCT','EL PRODUCTO')} title={t('Understands the guest.','Entiende al huésped.')} accent={t('Works for your hotel.','Trabaja para tu hotel.')} body={t('Voice and text conversations, feature-aware upgrades and useful memory. Requests, confirmations and outcomes in one place.','Conversaciones por voz y texto, mejoras según preferencias y memoria útil. Solicitudes, confirmaciones y resultados en un mismo lugar.')}/>
 <SalesDemoShowcase/>
 <Chapter id="memory" eyebrow={t('MEMORY & CONTEXT','MEMORIA Y CONTEXTO')} title={t('Remember what matters.','Recuerda lo que importa.')} body={t('Use what the guest has shared to make the next answer—and the next offer—more relevant.','Usa lo que comparte el huésped para hacer más relevante la siguiente respuesta y oferta.')} tint><MemoryPanel/><Details items={[{q:t('What does HC remember?','¿Qué recuerda HC?'),a:t('Current-stay requests and conversation context are separate from saved preferences. Reuse across visits or channels requires agreed identity checks, guest permission, access and retention settings. Guests can update or withdraw shared preferences. Human handoffs carry the relevant conversation context.','Solicitudes y contexto de la estancia se separan de preferencias guardadas. Reutilizar datos entre visitas o canales requiere identidad, permiso, acceso y retención acordados. Los huéspedes pueden actualizar o retirar preferencias. Las transferencias al equipo incluyen el contexto relevante.')} ]}/></Chapter>
 <Chapter id="control" eyebrow="COMPANION CONTROL" title={t('Your offers. Your rules. Your results.','Tus ofertas. Tus reglas. Tus resultados.')} body={t('Approve your offers. Follow confirmations. Understand the guest needs behind purchases and missed opportunities.','Aprueba ofertas. Sigue confirmaciones. Entiende las necesidades detrás de las compras y oportunidades perdidas.')}><ControlDashboard initialTab={2}/><Link className="xp-inline-link" href="/solutions#people">{t('Follow the guest-to-team handoff','Sigue la transferencia del huésped al equipo')}<ArrowRight size={16}/></Link><Details items={[{q:t('Who confirms and delivers a service?','¿Quién confirma y entrega el servicio?'),a:t('The hotel team or a validated connected system confirms availability, accepts requests and records completion. HC keeps the guest informed. Sent, accepted, confirmed, paid and delivered are different states; guest language must match the verified state.','El equipo o un sistema conectado validado confirma disponibilidad, acepta solicitudes y registra ejecución. HC informa al huésped. Enviado, aceptado, confirmado, pagado y entregado son estados distintos; el lenguaje debe coincidir con el estado verificado.')} ]}/></Chapter>
 <section className="hc-chapter hc-chapter-tint"><div className="xp-wrap"><VoiceSample/></div></section><FocusedPilot/></>
}

function Solutions() {
 const t=useWords()
 return <><PageIntro eyebrow={t('THE GUEST EXPERIENCE','LA EXPERIENCIA DEL HUÉSPED')} title={t('Your hotel,','Tu hotel,')} accent={t('wherever guests ask.','donde pregunte el huésped.')} body={t('Telephone, web and mobile first. In-room tablets when you want them.','Teléfono, web y móvil primero. Tablets en habitación cuando las quieras.')}/>
 <Chapter id="channels" eyebrow={t('CHOOSE THE CHANNEL','ELIGE EL CANAL')} title={t('One companion. Different ways in.','Un companion. Distintas formas de entrar.')}><ChannelStage/></Chapter>
 <Chapter id="people" eyebrow={t('GUEST EXPERIENCE. TEAM OWNERSHIP.','EXPERIENCIA DEL HUÉSPED. RESPONSABILIDAD DEL EQUIPO.')} title={t('Your team gets the next step.','Tu equipo recibe el siguiente paso.')} body={t('An upgrade and dinner in one conversation. A clear price, a confirmation for each item and a next step when plans change.','Una mejora y una cena en una conversación. Precio claro, confirmación por servicio y un siguiente paso si cambia el plan.')} tint><ServiceJourney staffPreview combined/><HandoffDetails/></Chapter>
 <Chapter id="channel-details" eyebrow={t('BEFORE YOU LAUNCH','ANTES DE LANZAR')} title={t('A few practical details.','Algunos detalles prácticos.')}><Details items={[
 {q:t('Do guests need an app or a tablet?','¿El huésped necesita una app o tablet?'),a:t('No app download is required for mobile or desktop web. Guests use a link or QR code. In-room tablets can be tailored to your property, including installation and device support. Voice availability depends on device, browser and configuration.','La web móvil y de escritorio no requiere descargar apps. Se accede por enlace o QR. Las tablets en la habitación se adaptan a tu hotel, incluida la instalación y el soporte de dispositivos. La voz depende de dispositivo, navegador y configuración.')},
 {q:t('What about telephone and WhatsApp?','¿Y el teléfono y WhatsApp?'),a:t('Telephone routing, transfers and supported actions are validated for each property. WhatsApp is an additional connection to assess, not an automatically enabled channel.','Rutas telefónicas, transferencias y acciones se validan por hotel. WhatsApp es una conexión adicional por evaluar, no un canal activado automáticamente.')},
 {q:t('How are languages and voice checked?','¿Cómo se prueban los idiomas y la voz?'),a:t('We agree the first guest languages, voice channel and hotel vocabulary, then test real questions, accents, names and handoffs with your team. A voice misunderstanding should lead to clarification or the agreed human route. Website voice also depends on browser and microphone support; guests can type instead. Channel and language coverage are signed off before launch.','Acordamos idiomas iniciales, canal de voz y vocabulario; probamos preguntas, acentos, nombres y transferencias con el equipo. Ante un malentendido, se pide aclaración o se usa la ruta humana acordada. La voz web depende del navegador y micrófono; el huésped puede escribir. Canales e idiomas se aprueban antes de lanzar.')},
 ]}/></Chapter><FocusedPilot/></>
}

function Revenue() {
 const t=useWords()
 return <><PageIntro eyebrow={t('REVENUE','INGRESOS')} title={t('Better recommendations.','Mejores recomendaciones.')} accent={t('More reasons to buy.','Más razones para comprar.')} body={t('Sell the balcony, the extra hour or the experience the guest wants. Recover missed opportunities. Measure what the hotel gains.','Ofrece el balcón, la hora extra o la experiencia que busca el huésped. Recupera oportunidades. Mide lo que gana el hotel.')}/>
 <Chapter id="recommendations" eyebrow={t('CAPTURE THE OPPORTUNITY','APROVECHA LA OPORTUNIDAD')} title={t('An offer that fits the guest.','Una oferta que encaja con el huésped.')}><RecoveryStory/><Details items={[{q:t('What makes a recommendation eligible?','¿Qué hace elegible una recomendación?'),a:t('Start with the guest’s expressed needs: a balcony, workspace, shorter treatment or later departure. Match them to verified room features and hotel-approved services, prices and availability. Included benefits and past purchases stay out of the sales prompts. Respect declines and pause offers during complaints. A specific room feature needs confirmed availability before it is promised.','Parte de lo que expresa el huésped: balcón, espacio de trabajo, tratamiento corto o salida más tarde. Relaciónalo con detalles verificados y servicios, precios y disponibilidad aprobados. Evita ofrecer beneficios incluidos o ya comprados. Respeta rechazos y pausa ofertas durante quejas. Un detalle específico requiere disponibilidad confirmada antes de prometerlo.')} ]}/></Chapter>
 <Chapter id="packages" eyebrow={t('HOTEL-APPROVED OFFERS','OFERTAS APROBADAS POR EL HOTEL')} title={t('Make the offer feel personal.','Haz que la oferta se sienta personal.')} tint><PhotoStory image="/assets/ui/dish-1.webp" alt={t('A hotel dining experience','Una experiencia gastronómica del hotel')} title={t('Dinner for two. A wine to match.','Cena para dos. El vino adecuado.')} body={t('Combine relevant services into a package your hotel approves. Keep the price, availability and margin under your control.','Combina servicios relevantes en un paquete aprobado. Mantén el control del precio, la disponibilidad y el margen.')}><div className="hc-return-pass"><span><RotateCcw size={21}/></span><div><small>{t('Optional return benefit','Beneficio opcional de regreso')}</small><strong>{t('A credit toward the next stay','Un crédito para la próxima estancia')}</strong></div></div><span className="hc-approved-label"><ShieldCheck size={16}/>{t('Your terms. Your approval.','Tus condiciones. Tu aprobación.')}</span></PhotoStory><Details items={[{q:t('Can an offer include a reason to return?','¿Puede una oferta dar una razón para volver?'),a:t('An optional return credit can follow an eligible completed purchase. The hotel sets validity, blackout dates, minimum spend and redemption limits. The benefit’s cost is included in the contribution calculation. HC does not invent unapproved discounts or combine services the hotel cannot fulfil.','Un crédito de regreso opcional puede seguir a una compra elegible completada. El hotel define vigencia, fechas excluidas, gasto mínimo y límites. El costo entra en el cálculo de contribución. HC no inventa descuentos ni combina servicios que el hotel no puede cumplir.')} ]}/></Chapter>
 <Chapter id="guest-demand" eyebrow={t('GUEST DEMAND','LO QUE BUSCAN TUS HUÉSPEDES')} title={t('See the opportunity behind the no.','Ve la oportunidad detrás del no.')} body={t('Learn what guests asked for, what got in the way and which alternatives deserve a place in your offers.','Conoce qué buscaban, qué impidió la compra y qué alternativas merecen formar parte de tus ofertas.')}><DemandInsight/><Details items={[{q:t('What turns a missed request into useful insight?','¿Qué convierte una solicitud sin resolver en información útil?'),a:t('The expressed need, the constraint, the alternative offered and the outcome. Keep guest statements separate from inferred reasons. Review patterns such as unavailable balconies, shorter spa visits or late departures to refine the hotel’s approved offers.','La necesidad expresada, la limitación, la alternativa y el resultado. Separa lo que dijo el huésped de los motivos inferidos. Revisa patrones como balcones no disponibles, visitas cortas al spa o salidas tardías para mejorar las ofertas aprobadas.')}]}/></Chapter>
 <Chapter id="measurement" eyebrow={t('THE ECONOMICS','LOS RESULTADOS ECONÓMICOS')} title={t('Measure what HC actually adds.','Mide lo que HC realmente aporta.')} body={t('Completed sales, after costs and an agreed comparison. Assisted revenue is reported separately.','Ventas completadas, después de costos y una comparación acordada. Las ventas asistidas se reportan aparte.')}><ContributionExample/></Chapter><FocusedPilot/></>
}

function Enterprise() {
 const t=useWords()
 const properties=[{image:'/assets/ui/suite-ocean.webp',title:t('Coastal resort','Resort costero')},{image:'/assets/editorial/hc-white-label-mexico-city.webp',title:t('City hotel','Hotel urbano')},{image:'/assets/editorial/hc-white-label-san-miguel.webp',title:t('Boutique retreat','Hotel boutique')}]
 return <><PageIntro eyebrow={t('FOR HOTEL GROUPS','PARA GRUPOS HOTELEROS')} title={t('Shared standards.','Estándares compartidos.')} accent={t('Distinctive hotels.','Hoteles con identidad propia.')} body={t('One approach across your portfolio. Each hotel keeps its own voice, knowledge, offers and team.','Un enfoque para el portafolio. Cada hotel conserva su voz, conocimiento, ofertas y equipo.')}/>
 <Chapter id="portfolio" eyebrow={t('BUILT AROUND EACH PROPERTY','ADAPTADO A CADA HOTEL')} title={t('Every hotel still feels like itself.','Cada hotel conserva su identidad.')}><div className="hc-property-gallery">{properties.map(p=><figure key={p.title}><Image src={p.image} alt={p.title} width={650} height={800} sizes="(max-width:800px) 90vw, 30vw"/><figcaption>{p.title}</figcaption></figure>)}</div><small className="hc-visual-caption">{t('Illustrative property configurations','Configuraciones ilustrativas de hoteles')}</small></Chapter>
 <Chapter id="governance" eyebrow={t('GROUP CONTROL','CONTROL DEL GRUPO')} title={t('Set the standards. Keep local ownership.','Define estándares. Conserva responsables locales.')} body={t('Shared standards for offers and service. Property-level context to understand requests, guest preferences and commercial opportunities.','Estándares compartidos para ofertas y servicio. Contexto por hotel para entender solicitudes, preferencias y oportunidades comerciales.')} tint><PortfolioPreview/><Details items={[
 {q:t('What can a group see across its hotels?','¿Qué ve un grupo entre sus hoteles?'),a:t('The portfolio view brings together guest conversations, open requests, stay inquiries and accepted offers for properties the user is authorized to manage. Each property has its own knowledge, offers, voice profiles and configuration. These are operational counts; revenue lift is assessed separately using the pilot’s agreed method.','La vista reúne conversaciones, solicitudes abiertas, consultas y ofertas aceptadas de los hoteles autorizados. Cada hotel conserva conocimiento, ofertas, voces y configuración. Son conteos operativos; el incremento de ingresos se evalúa con el método del piloto.')},
 {q:t('How do guest needs improve our offers?','¿Cómo mejoran las ofertas las necesidades de los huéspedes?'),a:t('Review expressed interests, reasons for declining and unavailable first choices by property. Use the patterns to refine approved offers while keeping local availability, costs and guest preferences in view.','Revisa intereses expresados, motivos de rechazo y primeras opciones no disponibles por hotel. Usa patrones para mejorar ofertas aprobadas conservando disponibilidad, costos y preferencias locales.')},
 {q:t('How are hotel knowledge and updates managed?','¿Cómo se gestionan el conocimiento y los cambios?'),a:t('Assign hotel or department owners to policies, services and prices. Review updates before publishing and keep a record of important changes. Define shared standards and what may vary locally.','Asigna responsables de políticas, servicios y precios por hotel o área. Revisa antes de publicar y registra cambios importantes. Define estándares comunes y qué puede variar localmente.')},
 {q:t('Who can access each property’s information?','¿Quién accede a la información de cada hotel?'),a:t('Roles specify who can view, approve and change information. Property boundaries, ownership and group-level reporting are validated during setup. Use common outcome definitions while keeping property differences visible.','Los roles definen quién ve, aprueba y cambia información. Límites por hotel, propiedad y reportes del grupo se validan durante la configuración. Usa definiciones comunes de resultados conservando diferencias entre hoteles.')},
 {q:t('How are guest memory and payments handled?','¿Cómo se gestionan memoria y pagos?'),a:t('Stay context and saved preferences are separate. Identity, guest permission, retention and deletion are agreed before reuse across visits or channels. For enabled Stripe checkout, card details go directly to Stripe; HC receives a tokenized reference. Payment actions require a validated connection. Review current controls in the trust center during procurement.','Contexto y preferencias guardadas se separan. Identidad, permiso, retención y eliminación se acuerdan antes de reutilizar datos. En checkout de Stripe habilitado, los datos de tarjeta van a Stripe; HC recibe una referencia tokenizada. Los pagos requieren conexión validada. Revisa controles actuales en el centro de confianza.')},
 ]}/><Link className="xp-inline-link" href="/trust">{t('Explore the trust center','Explora el centro de confianza')}<ArrowRight size={16}/></Link></Chapter>
 <div id="rollout"><OnboardingTimeline/></div><FocusedPilot/></>
}

function Implementation() {
 const t=useWords()
 return <><PageIntro eyebrow={t('SETUP & PILOT','CONFIGURACIÓN Y PILOTO')} title={t('Start at one hotel.','Empieza en un hotel.')} accent={t('Expand on the evidence.','Amplía con evidencia.')} body={t('A defined guest journey, approved rules and a clear way to measure value.','Una experiencia definida, reglas aprobadas y una forma clara de medir valor.')}/>
 <OnboardingTimeline/><HotelConnections/>
 <Chapter eyebrow={t('THE PROPOSED PILOT','EL PILOTO PROPUESTO')} title={t('Agree what counts. Then measure it.','Acordar qué cuenta. Después medirlo.')}><PilotTerms/><Details items={[
 {q:t('How do we handle reliability and service exceptions?','¿Cómo se gestionan fiabilidad y excepciones?'),a:t('The connection plan names supported actions, confirmation checks, support contacts, notification destinations and the fallback when a system or staff route is unavailable. Browser workflows are validated for the hotel’s access and interface. Support coverage, response targets and recovery responsibilities are agreed in writing; they are not inferred from a software logo.','El plan identifica acciones, verificaciones de confirmación, soporte, destinos de notificación y alternativas ante sistemas o rutas no disponibles. Los flujos de navegador se validan para el acceso e interfaz del hotel. Cobertura, tiempos objetivo y recuperación se acuerdan por escrito; no se deducen de un logotipo.')},
 {q:t('How quickly can we launch?','¿Qué tan rápido podemos lanzar?'),a:t('Timing depends on approved knowledge, channels, staff preparation, system access and the chosen scope. We rehearse real scenarios and handoffs with the team before guest launch. A narrow web pilot can be simpler than telephone or transactional integrations.','El plazo depende de conocimiento aprobado, canales, preparación, acceso y alcance. Ensayamos escenarios y transferencias con el equipo antes de activar. Un piloto web acotado puede ser más sencillo que telefonía o integraciones transaccionales.')},
 {q:t('Which integrations and actions are included?','¿Qué integraciones y acciones se incluyen?'),a:t('Live inventory, reservation changes and payments are included only when the specific connection and permissions have been validated. Telephone routing and extra messaging channels are scoped too. We agree content maintenance, support and fallback responsibilities before launch.','Inventario en vivo, cambios de reservas y pagos solo se incluyen al validar conexión y permisos. También se definen telefonía y mensajería adicional. Acordamos mantenimiento de contenido, soporte y alternativas antes de lanzar.')},
 {q:t('Will HC replace our staff or PMS?','¿HC reemplaza al equipo o PMS?'),a:t('HC works with the systems and people already serving the hotel. It handles approved information and requests; your team retains responsibility for service, judgment and confirmation.','HC trabaja con los sistemas y personas que ya atienden el hotel. Gestiona información y solicitudes aprobadas; el equipo conserva responsabilidad de servicio, criterio y confirmación.')},
 ]}/></Chapter></>
}

function Company() {
 const t=useWords()
 return <><PageIntro eyebrow={t('BUILT BY AXIONARI','CREADO POR AXIONARI')} title={t('Better technology.','Mejor tecnología.')} accent={t('More human hospitality.','Hospitalidad más humana.')} body={t('Help hotels pay better attention to guests—and make the commercial value clear.','Ayudar a los hoteles a atender mejor y hacer claro el valor comercial.')}/>
 <Chapter eyebrow={t('WHAT WE BELIEVE','EN QUÉ CREEMOS')} title={t('Attention is the point.','La atención es el propósito.')}><PhotoStory image="/assets/img/company-reception.webp" alt={t('A thoughtful hotel welcome','Una bienvenida atenta en el hotel')} title={t('Give the team more room to care.','Dale al equipo más espacio para cuidar.')} body={t('Let AI handle routine questions and relevant recommendations. Let people bring judgment, reassurance and personal attention.','Que la IA atienda preguntas rutinarias y recomendaciones relevantes. Que las personas aporten criterio, tranquilidad y atención personal.')}/></Chapter>
 <Chapter id="principles" eyebrow={t('OUR PRINCIPLES','NUESTROS PRINCIPIOS')} title={t('Useful. Personal. Accountable.','Útil. Personal. Responsable.')} tint><div className="hc-principles">{[{title:t('Useful service','Servicio útil'),body:t('Make the next step easier. Keep a person within reach.','Facilita el siguiente paso. Mantén una persona al alcance.')},{title:t('Memory with permission','Memoria con permiso'),body:t('Remember what helps. Let guests choose what they share.','Recuerda lo útil. Deja al huésped elegir qué comparte.')},{title:t('Value you can assess','Valor que puedes evaluar'),body:t('Respect hotel rules. Measure completed outcomes and additional contribution.','Respeta las reglas. Mide resultados completados y contribución adicional.')}].map(p=><div key={p.title}><h3>{p.title}</h3><p>{p.body}</p></div>)}</div></Chapter>
 <Chapter id="responsibility" eyebrow={t('TRUST','CONFIANZA')} title={t('Clear responsibilities.','Responsabilidades claras.')}><div className="hc-trust-links">{[{href:'/trust',label:t('Trust center','Centro de confianza')},{href:'/responsible-ai',label:t('Responsible AI','IA responsable')},{href:'/privacy',label:t('Privacy','Privacidad')}].map(l=><Link key={l.href} href={l.href}><ShieldCheck size={20}/><span>{l.label}</span><ArrowRight size={18}/></Link>)}</div></Chapter><FocusedPilot/></>
}

function Contact() {
 const t=useWords()
 return <><PageIntro eyebrow={t('LET’S TALK','CONVERSEMOS')} title={t('Bring us your hotel.','Cuéntanos de tu hotel.')} accent={t('Let’s find the first opportunity.','Encontremos la primera oportunidad.')} body={t('Explore the experience, ask a question or discuss a scoped pilot.','Explora la experiencia, pregunta o hablemos de un piloto definido.')}/><section className="hc-chapter"><div className="xp-wrap hc-contact-options"><div><h2>{t('Sales & pilots','Ventas y pilotos')}</h2><p>{t('A presentation shaped around your hotel.','Una presentación enfocada en tu hotel.')}</p><Link className="xp-button" href="/demo">{t('Request a presentation','Solicita una presentación')}<ArrowRight size={16}/></Link><a href="mailto:sales@axionari.com">sales@axionari.com</a></div><div><h2>{t('Customer support','Soporte a clientes')}</h2><p>{t('Already working with HC? Reach our team.','¿Ya trabajas con HC? Contacta al equipo.')}</p><a href="mailto:support@axionari.com">support@axionari.com</a></div></div></section></>
}

export default function ExperiencePage({page}:{page:ExperiencePageKey}) {
 const Page={platform:Platform,solutions:Solutions,revenue:Revenue,enterprise:Enterprise,implementation:Implementation,company:Company,contact:Contact}[page]
 return <ExperienceFrame><Page/></ExperienceFrame>
}
