'use client'

import { useEffect, useId, useRef, useState, type ReactNode } from 'react'
import { ArrowRight, Check, CheckCheck, ChevronRight, Globe2, Headphones, Heart, LayoutDashboard, MessageCircle, Mic, Monitor, Pause, Phone, Play, Plus, ShieldCheck, Smartphone, Sparkles, Tablet, Users, Volume2 } from 'lucide-react'
import { LocalizedLink as Link } from '@/components/LocalizedLink'
import { useLang } from '@/lib/i18n/LanguageContext'
import transcript from './voice-transcript.json'
import { DemandInsight } from './DemandInsight'
import { SalesDemoTeaser } from './SalesDemoShowcase'
import './experience.css'

export function useWords() { const { lang } = useLang(); return (en: string, es: string) => lang === 'es' ? es : en }

export function Eyebrow({ children }: { children: ReactNode }) { return <p className="xp-eyebrow">{children}</p> }
export function SectionHeading({ eyebrow, title, body, children }: { eyebrow: string; title: string; body?: string; children?: ReactNode }) {
  return <div className="xp-section-head"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div><div>{body && <p>{body}</p>}{children}</div></div>
}
export function Action({ href='/demo', children, quiet=false }: { href?: string; children: ReactNode; quiet?: boolean }) {
  return <Link href={href} className={`xp-button ${quiet ? 'xp-button-quiet' : ''}`}>{children}<ArrowRight size={17} aria-hidden="true" /></Link>
}
export function Tabs({ labels, active, onChange, name }: { labels: string[]; active: number; onChange: (i: number) => void; name: string }) {
  return <div className="xp-tabs" role="tablist" aria-label={name}>{labels.map((label,i)=><button key={label} id={`${name}-tab-${i}`} role="tab" type="button" aria-selected={active===i} aria-controls={`${name}-panel`} tabIndex={active===i?0:-1} onClick={()=>onChange(i)} onKeyDown={event=>{
    let next=i
    if(event.key==='ArrowRight') next=(i+1)%labels.length
    else if(event.key==='ArrowLeft') next=(i+labels.length-1)%labels.length
    else if(event.key==='Home') next=0
    else if(event.key==='End') next=labels.length-1
    else return
    event.preventDefault(); onChange(next); document.getElementById(`${name}-tab-${next}`)?.focus()
  }}>{label}</button>)}</div>
}

export function Wave({ playing=false }: { playing?: boolean }) {
  return <div className="xp-wave" data-playing={playing} aria-hidden="true">{[12,22,34,18,44,30,52,20,38,54,30,16,44,24,50,36,18,32,48,26,40,18,30,50,26,16,36,22,46,30,18,42].map((height,i)=><i key={i} style={{height,animationDelay:`${i*-.11}s`}} />)}</div>
}

const scenes = {
 en: [
  {label:'Telephone',tag:'BEFORE THE STAY',title:'Every call is a chance to help.',ask:'Do you have a quiet room with an ocean view?',reply:'Let’s find the right room. The Ocean King and Ocean Suite are in the quieter wing.',action:'Room options, ready to explore',context:'Quiet room · Ocean view',image:'/assets/ui/suite-ocean.webp',surface:'phone'},
  {label:'Web & mobile',tag:'DURING THE STAY',title:'A request, without the wait.',ask:'Could we have extra towels in room 204?',reply:'I’ll send your request to housekeeping. You can see its status here.',action:'Housekeeping request sent',context:'Room 204 · Preferred language: English',image:'/assets/img/luxury-lobby-800.webp',surface:'mobile'},
  {label:'Relevant offers',tag:'THE RIGHT MOMENT',title:'An offer that fits the guest.',ask:'Somewhere special for our anniversary?',reply:'The terrace dinner could be lovely. Would you like to see the menu and available times?',action:'Terrace dinner · View details',context:'Anniversary · Vegetarian preference',image:'/assets/ui/dish-1.webp',surface:'web'},
  {label:'In-room tablet',tag:'AN OPTIONAL TOUCHPOINT',title:'Speak. Tap. Enjoy your stay.',ask:'What can we do this afternoon?',reply:'A spa treatment, a walk by the beach, or something to eat? What sounds good?',action:'Spa · Dining · Local experiences',context:'Room 204 · Current stay',image:'/assets/ui/spa-1.webp',surface:'tablet'},
  {label:'Memory & context',tag:'THE NEXT CONVERSATION',title:'A familiar welcome.',ask:'We’re thinking of coming back in October.',reply:'Shall we look for another quiet room? You can update your preferences at any time.',action:'Relevant context, with permission',context:'Quiet room · Guest-approved preferences',image:'/assets/ui/suite-garden.webp',surface:'memory'},
 ],
 es: [
  {label:'Teléfono',tag:'ANTES DE LA ESTANCIA',title:'Cada llamada es una oportunidad.',ask:'¿Tienen una habitación tranquila con vista al mar?',reply:'Busquemos la ideal. La Habitación Marina y la Suite del Mar están en la zona tranquila.',action:'Opciones de habitación para explorar',context:'Zona tranquila · Vista al mar',image:'/assets/ui/suite-ocean.webp',surface:'phone'},
  {label:'Web y móvil',tag:'DURANTE LA ESTANCIA',title:'Una solicitud, sin esperas.',ask:'¿Podrían traer toallas extra a la habitación 204?',reply:'Enviaré tu solicitud a limpieza. Puedes consultar su estado aquí.',action:'Solicitud enviada a limpieza',context:'Habitación 204 · Idioma: español',image:'/assets/img/luxury-lobby-800.webp',surface:'mobile'},
  {label:'Ofertas relevantes',tag:'EL MOMENTO ADECUADO',title:'Una oferta que encaja contigo.',ask:'¿Algo especial para nuestro aniversario?',reply:'La cena en la terraza podría ser ideal. ¿Quieres ver el menú y los horarios disponibles?',action:'Cena en la terraza · Ver detalles',context:'Aniversario · Preferencia vegetariana',image:'/assets/ui/dish-1.webp',surface:'web'},
  {label:'Tablet en habitación',tag:'UN CANAL OPCIONAL',title:'Habla. Toca. Disfruta.',ask:'¿Qué podemos hacer esta tarde?',reply:'¿Un tratamiento de spa, un paseo por la playa o algo de comer? ¿Qué se te antoja?',action:'Spa · Restaurante · Experiencias',context:'Habitación 204 · Estancia actual',image:'/assets/ui/spa-1.webp',surface:'tablet'},
  {label:'Memoria y contexto',tag:'LA SIGUIENTE CONVERSACIÓN',title:'Una bienvenida familiar.',ask:'Estamos pensando en volver en octubre.',reply:'¿Buscamos otra habitación tranquila? Puedes actualizar tus preferencias cuando quieras.',action:'Contexto relevante, con permiso',context:'Zona tranquila · Preferencias autorizadas',image:'/assets/ui/suite-garden.webp',surface:'memory'},
 ]
}

export function GuestScene({ index=0, compact=false }: { index?: number; compact?: boolean }) {
  const {lang}=useLang(), t=useWords(), scene=scenes[lang][index]
  return <div className={`xp-guest-scene ${compact?'xp-guest-compact':''}`} data-surface={scene.surface}>
    <div className="xp-scene-photo" style={{backgroundImage:`url(${scene.image})`}} aria-hidden="true" />
    <div className="xp-scene-caption"><span>{scene.tag}</span><strong>{scene.title}</strong></div>
    <div className="xp-device" key={`${lang}-${index}`}>
      <div className="xp-device-bar"><div><span className="xp-hc-symbol">h</span><span><b>Casa del Mar</b><small>Hotel Companion</small></span></div>{scene.surface==='phone'?<Phone size={17} />:scene.surface==='tablet'?<Tablet size={17} />:<MessageCircle size={17} />}</div>
      {scene.surface==='phone' && <div className="xp-call-state"><span className="xp-orb"><Mic size={23} /></span><span>{t('A natural conversation','Una conversación natural')}</span><Wave playing /></div>}
      <div className="xp-conversation"><div className="xp-guest-bubble"><small>{t('Guest','Huésped')}</small><p>{scene.ask}</p></div><div className="xp-host-bubble"><span><Sparkles size={13} /> Companion</span><p>{scene.reply}</p></div><div className="xp-scene-result"><Check size={15} /><span>{scene.action}</span><ChevronRight size={14} /></div></div>
      <div className="xp-device-input"><span>{t('Ask anything about your stay…','Pregunta sobre tu estancia…')}</span><Mic size={16} /></div>
    </div>
    <div className="xp-context-toast"><Heart size={15} /><div><span>{t('CONTEXT THAT CARRIES FORWARD','CONTEXTO QUE TE ACOMPAÑA')}</span><strong>{scene.context}</strong></div><CheckCheck size={15} /></div>
  </div>
}

export function HeroExperience() {
 const t=useWords()
 return <section className="xp-hero" id="home"><div className="xp-wrap xp-hero-grid"><div className="xp-hero-copy"><Eyebrow>{t('EVERY CONVERSATION. A BETTER STAY.','CADA CONVERSACIÓN. UNA MEJOR ESTANCIA.')}</Eyebrow><h1>{t('The stay','La estancia')}<br/><span>{t('remembers.','recuerda.')}</span></h1><p>{t('An AI companion that answers your guests, arranges hotel services and recommends what fits. By voice or text, remembering the details that make the next conversation better.','Un companion con IA que responde a tus huéspedes, coordina servicios y recomienda lo que encaja. Por voz o texto, recordando los detalles que mejoran la siguiente conversación.')}</p><div className="xp-hero-benefit">{t('Better service. More opportunities to earn.','Mejor atención. Más oportunidades de ingresos.')}</div><div className="xp-actions"><Action href="/implementation#pilot-terms">{t('Explore your pilot','Explora tu piloto')}</Action><Action quiet>{t('Request a demo','Solicita una demo')}</Action></div><div className="xp-hero-note"><span className="xp-dot"/>{t('Telephone · Web · Mobile · In-Room Tablets','Teléfono · Web · Móvil · Tablets en la habitación')}</div><a className="xp-hero-listen" href="#hear-it"><Headphones size={14}/>{t('Hear a real voice sample','Escucha una muestra de voz')}</a></div><SalesDemoTeaser/></div></section>
}

export function PilotInvitation(){
 const t=useWords()
 return <section className="xp-pilot-invitation" aria-labelledby="pilot-invitation-title"><div className="xp-wrap xp-pilot-invitation-grid"><div><Eyebrow>{t('THE OUTCOME-BASED PILOT','EL PILOTO BASADO EN RESULTADOS')}</Eyebrow><h2 id="pilot-invitation-title">{t('Prove the value before you roll out.','Demuestra el valor antes de ampliar.')}</h2><p>{t('One hotel. One agreed journey. No upfront software or standard setup fee for the agreed pilot scope.','Un hotel. Una experiencia acordada. Sin pago inicial de software ni configuración estándar para el alcance del piloto.')}</p></div><div><strong>{t('No verified lift. No success fee.','Sin incremento verificado. Sin comisión de éxito.')}</strong><p>{t('We earn an agreed share of the extra contribution HC generates, after costs and refunds. Your team provides approved hotel information, a service owner and the records needed to measure it.','Recibimos un porcentaje acordado de la contribución adicional generada por HC, después de costos y devoluciones. Tu equipo aporta información aprobada, un responsable y registros para medirla.')}</p><Link className="xp-inline-link" href="/implementation#pilot-terms">{t('See the pilot terms','Ver condiciones del piloto')}<ArrowRight size={16}/></Link><small>{t('Eligibility, scope and measurement agreed before launch. Custom integrations and optional hardware quoted separately.','Elegibilidad, alcance y medición acordados antes de lanzar. Integraciones especiales y hardware opcional cotizados aparte.')}</small></div></div></section>
}

export function OutcomeEvidence(){
 const t=useWords()
 return <div className="xp-outcome-evidence">{[
  {label:t('SERVICE','SERVICIO'),title:t('Did the guest get help?','¿Se atendió al huésped?'),body:t('Track requests accepted, completed and confirmed. Review unresolved requests and handoffs with the hotel team.','Registra solicitudes aceptadas, completadas y confirmadas. Revisa pendientes y transferencias con el equipo.')},
  {label:t('REVENUE','INGRESOS'),title:t('What was fulfilled and paid?','¿Qué se completó y cobró?'),body:t('Reconcile completed sales with hotel records. Subtract delivery costs, refunds and redeemed benefits.','Concilia ventas completadas con registros del hotel. Descuenta costos, devoluciones y beneficios utilizados.')},
  {label:t('ADDITIONAL VALUE','VALOR ADICIONAL'),title:t('What did HC actually add?','¿Qué aportó HC realmente?'),body:t('Compare against the method agreed before launch. An assisted sale alone does not prove additional revenue.','Compara con el método acordado antes del lanzamiento. Una venta asistida no demuestra ingreso adicional.')},
 ].map(item=><article key={item.label}><span>{item.label}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}<p className="xp-evidence-note">{t('These are the pilot measures, not claimed customer results. See the full product in a scheduled presentation; agree the evidence for your hotel before launch.','Estas son medidas del piloto, no resultados de clientes. Conoce el producto completo en una presentación agendada y acuerda la evidencia de tu hotel antes de lanzar.')}</p></div>
}

export function CapabilityExplorer() {
 const t=useWords(), [active,setActive]=useState(0)
 const items=[
  {label:t('Answer & guide','Responder y orientar'),title:t('Turn questions into a great first impression.','Convierte preguntas en una gran primera impresión.'),body:t('Room questions, arrival details, hotel policies, local recommendations. Give guests useful answers from your hotel’s own approved knowledge.','Habitaciones, llegadas, políticas y recomendaciones locales. Respuestas útiles basadas en el conocimiento aprobado por tu hotel.'),features:[t('Natural voice and text','Voz y texto naturales'),t('Your hotel’s tone and languages','El tono e idiomas de tu hotel'),t('A person when the guest needs one','Una persona cuando el huésped la necesita')],scene:0},
  {label:t('Handle requests','Gestionar solicitudes'),title:t('Get the request to the right team.','Envía cada solicitud al equipo correcto.'),body:t('Collect the details, pass along the context, and keep the guest informed. Staff confirm service availability and completion.','Recopila los detalles, comparte el contexto y mantén informado al huésped. Tu equipo confirma la disponibilidad y la ejecución.'),features:[t('Housekeeping, dining and front desk','Limpieza, restaurante y recepción'),t('A clear owner and request status','Responsable y estado claros'),t('Human handoff with context','Transferencia al equipo con contexto')],scene:1},
  {label:t('Offer & earn','Recomendar y vender'),title:t('Make the useful recommendation.','Haz la recomendación útil.'),body:t('Recommend hotel-approved services around the guest’s interests, timing and availability. Combine relevant services into an approved package when it makes sense.','Recomienda servicios aprobados según intereses, momento y disponibilidad. Combina servicios relevantes en un paquete autorizado cuando tenga sentido.'),features:[t('Contextual recommendations','Recomendaciones con contexto'),t('Approved packages and offers','Paquetes y ofertas aprobados'),t('Margin and guest preference rules','Reglas de margen y preferencias')],scene:2},
  {label:t('Remember & return','Recordar y recibir'),title:t('Let the next conversation start further ahead.','Que la siguiente conversación empiece mejor.'),body:t('Carry relevant context through the stay. For returning guests, reuse only the preferences they allow, with identity and retention settings agreed at setup.','Conserva el contexto útil durante la estancia. Para huéspedes que regresan, reutiliza solo las preferencias que autoricen, con identidad y retención definidas al configurar.'),features:[t('Stay context and guest preferences','Contexto y preferencias'),t('Guest permission and edit controls','Permiso y actualización de datos'),t('Less repeating. More recognition.','Menos repeticiones. Más reconocimiento.')],scene:4},
 ]
 const item=items[active]
 return <div className="xp-capabilities"><Tabs labels={items.map(i=>i.label)} active={active} onChange={setActive} name="capabilities" /><div className="xp-capability-panel" id="capabilities-panel" role="tabpanel" aria-labelledby={`capabilities-tab-${active}`}><div className="xp-capability-copy" key={active}><span className="xp-index">0{active+1} / 04</span><h3>{item.title}</h3><p>{item.body}</p><ul>{item.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><Link className="xp-inline-link" href={active===2?'/revenue':active===3?'/platform#memory':'/platform'}>{t('Explore the product','Explora el producto')}<ArrowRight size={16}/></Link></div><GuestScene index={item.scene} compact /></div></div>
}

export function VoiceSample() {
 const t=useWords(), {lang}=useLang(), audio=useRef<HTMLAudioElement>(null), [playing,setPlaying]=useState(false), [time,setTime]=useState(0), [duration,setDuration]=useState(0), [error,setError]=useState(false), uid=useId()
 const lines=transcript[lang]
 const sampleDuration=duration||lines[lines.length-1].end
 async function seek(seconds:number){
  const current=audio.current;if(!current)return
  if(current.readyState===0){
   current.load()
   try{await new Promise<void>((resolve,reject)=>{
    const loaded=()=>{cleanup();resolve()},failed=()=>{cleanup();reject(new Error("Audio unavailable"))}
    const cleanup=()=>{current.removeEventListener("loadedmetadata",loaded);current.removeEventListener("error",failed)}
    current.addEventListener("loadedmetadata",loaded,{once:true});current.addEventListener("error",failed,{once:true})
   })}catch{setError(true);return}
  }
  if(audio.current!==current)return
  current.currentTime=seconds;setTime(seconds)
 }
 async function toggle(){ if(!audio.current) return; if(playing) audio.current.pause();else{setError(false);try{await audio.current.play()}catch{setError(true)}} }
 useEffect(()=>{const current=audio.current;const stop=()=>{if(document.hidden) current?.pause()};document.addEventListener('visibilitychange',stop);return()=>document.removeEventListener('visibilitychange',stop)},[lang])
 const format=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`
 return <div className="xp-voice-sample" id="hear-it"><div className="xp-voice-art"><div className="xp-voice-heading"><Headphones size={19}/><span>{t('A conversation, not a phone menu.','Una conversación, no un menú telefónico.')}</span></div><div className="xp-voice-center"><span className="xp-large-orb"><Mic size={32}/></span><Wave playing={playing}/><span>{t('Guest + Hotel Companion','Huésped + Hotel Companion')}</span></div><audio key={lang} ref={audio} src={`/assets/experience/voice-${lang}.mp3`} preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onEmptied={()=>{setDuration(0);setTime(0);setPlaying(false);setError(false)}} onError={()=>setError(true)} /><div className="xp-audio-controls"><button onClick={toggle} type="button" className="xp-audio-play" aria-label={playing?t('Pause voice sample','Pausar muestra de voz'):t('Play voice sample','Reproducir muestra de voz')}>{playing?<Pause size={19}/>:<Play size={19}/>}</button><div><label className="xp-sr-only" htmlFor={uid}>{t('Seek voice sample','Posición de la muestra')}</label><input id={uid} type="range" min="0" max={sampleDuration} step="0.1" value={Math.min(time,sampleDuration)} onChange={e=>void seek(Number(e.target.value))}/><span>{format(time)}<b>{format(sampleDuration)}</b></span></div><Volume2 size={17} aria-hidden="true" /></div>{error && <p role="alert">{t('The sample could not play. Please try again.','No se pudo reproducir. Intenta de nuevo.')}</p>}<small>{t('Recorded example · Sample hotel · English','Ejemplo grabado · Hotel de muestra · Español')}</small></div><div className="xp-voice-transcript"><Eyebrow>{t('LISTEN. READ. EXPERIENCE.','ESCUCHA. LEE. EXPERIMENTA.')}</Eyebrow><h3>{t('It listens to what matters.','Escucha lo que importa.')}</h3><div>{lines.map((line,i)=><button key={`${lang}-${i}`} type="button" data-current={time>=line.start&&time<line.end&&playing} onClick={()=>void seek(line.start)} aria-label={`${t('Seek to','Ir a')}: ${line.text}`}><span>{line.role==='guest'?t('Guest','Huésped'):'Companion'}</span><p>{line.text}</p></button>)}</div></div></div>
}

export function ControlDashboard({ initialTab=0 }: { initialTab?: number }) {
 const t=useWords(), [active,setActive]=useState(initialTab)
 const titles=[t('Requests','Solicitudes'),t('Guest context','Contexto'),t('Offers & rules','Ofertas y reglas'),t('Guest demand','Necesidades'),t('Results','Resultados')]
 return <div className="xp-control"><div className="xp-control-header"><span><LayoutDashboard size={17}/> Companion Control</span><small>{t('Illustrative workspace','Espacio ilustrativo')}</small></div><div className="xp-control-layout"><aside className="xp-control-sidebar"><div className="xp-hotel-switch"><span className="xp-hc-symbol">h</span><div>Casa del Mar<small>{t('Property workspace','Espacio del hotel')}</small></div></div><Tabs labels={titles} active={active} onChange={setActive} name="control-view"/><div className="xp-control-sidebar-note"><ShieldCheck size={18}/><span>{t('Your rules. Your team. Your hotel.','Tus reglas. Tu equipo. Tu hotel.')}</span></div></aside><div className="xp-control-content" id="control-view-panel" role="tabpanel" aria-labelledby={`control-view-tab-${active}`} key={active}><div className="xp-control-page-head"><div><Eyebrow>CASA DEL MAR</Eyebrow><h3>{titles[active]}</h3></div><span className="xp-control-avatar">AM</span></div>
 {active===0?<><div className="xp-control-metrics">{[[t('New request','Nueva solicitud'),'01'],[t('In progress','En proceso'),'02'],[t('Ready for review','Por revisar'),'01']].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className="xp-request-table">{[[t('Extra towels','Toallas extra'),'204',t('Housekeeping','Limpieza'),t('Assigned','Asignada')],[t('Terrace dinner','Cena en terraza'),'118',t('Restaurant','Restaurante'),t('Needs confirmation','Por confirmar')],[t('Airport transfer','Traslado aeropuerto'),'306',t('Front desk','Recepción'),t('In progress','En proceso')]].map(([request,room,team,status],i)=><div className="xp-request-row" key={request}><span className="xp-request-icon">{i===0?<Check size={16}/>:i===1?<Heart size={16}/>:<Phone size={16}/>}</span><div><b>{request}</b><small>{t('Room','Habitación')} {room} · {team}</small></div><span>{status}</span><ChevronRight size={14}/></div>)}</div><div className="xp-control-note"><MessageCircle size={17}/>{t('The team receives the request and the conversation context.','El equipo recibe la solicitud y el contexto de la conversación.')}</div></>:
 active===1?<div className="xp-memory-workspace"><div className="xp-guest-profile"><span className="xp-profile-avatar">JL</span><h4>Jamie L.</h4><p>{t('Current stay · Room 204','Estancia actual · Habitación 204')}</p><span className="xp-badge">{t('Preferences shared by guest','Preferencias compartidas')}</span></div><div className="xp-memory-list">{[[t('Trip occasion','Motivo del viaje'),t('Anniversary','Aniversario')],[t('Room preference','Habitación preferida'),t('Quiet area · Ocean view','Zona tranquila · Vista al mar')],[t('Dining preference','Preferencia gastronómica'),t('Vegetarian options','Opciones vegetarianas')],[t('Use next time?','¿Usar en otra visita?'),t('Only with guest permission','Solo con permiso del huésped')]].map(([key,value])=><div key={key}><small>{key}</small><strong>{value}</strong><Check size={15}/></div>)}</div></div>:
 active===2?<><div className="xp-offer-rule"><div className="xp-offer-photo" style={{backgroundImage:'url(/assets/ui/suite-garden.webp)'}}/><div><span className="xp-badge">{t('HOTEL-APPROVED OFFER','OFERTA APROBADA')}</span><h4>{t('A balcony for morning coffee','Un balcón para el café')}</h4><p>{t('Private balcony · Garden-facing room','Balcón privado · Habitación hacia el jardín')}</p></div></div><div className="xp-rule-grid">{[[t('When it fits','Cuándo encaja'),t('Expressed interest in a balcony','Interés expresado en un balcón')],[t('Protect the margin','Proteger el margen'),t('Approved supplement + margin floor','Suplemento aprobado + margen mínimo')],[t('Respect the guest','Respetar al huésped'),t('No offer after a decline or complaint','Sin ofertas tras rechazos o quejas')],[t('Confirm fulfilment','Confirmar ejecución'),t('Verify the feature for the full stay','Verificar el detalle para toda la estancia')]].map(([key,value])=><div key={key}><ShieldCheck size={17}/><small>{key}</small><strong>{value}</strong></div>)}</div></>:
 active===3?<DemandInsight compact/>:
 <><div className="xp-results-title"><span>{t('Additional contribution','Contribución adicional')}</span><strong>$3,000<small>{t('Example, not a forecast','Ejemplo, no pronóstico')}</small></strong></div><div className="xp-result-bars">{[32,48,43,67,52,82,74,96].map((height,i)=><div key={i}><span style={{height:`${height}%`,animationDelay:`${i*.06}s`}}/></div>)}</div><div className="xp-results-foot"><span>{t('Completed sales, costs and refunds','Ventas completadas, costos y devoluciones')}</span><span>{t('Compared with an agreed baseline','Comparadas con una base acordada')}</span></div></>}
 </div></div></div>
}

export function SetupExplorer() {
 const t=useWords(),[active,setActive]=useState(0)
 const steps=[{title:t('Learn your hotel','Conocer tu hotel'),text:t('Your policies, rooms, services, tone and languages. One approved source of hotel knowledge.','Políticas, habitaciones, servicios, tono e idiomas. Una fuente aprobada de conocimiento hotelero.'),items:[t('Hotel knowledge','Conocimiento del hotel'),t('Services & prices','Servicios y precios'),t('Guest experience standards','Estándares de atención')],icon:Globe2}, {title:t('Connect & set rules','Conectar y definir reglas'),text:t('Choose the first channels. Map requests, system access, guest permissions and offer limits with your team.','Elige los primeros canales. Define solicitudes, acceso a sistemas, permisos y límites de ofertas con tu equipo.'),items:[t('Channels & system access','Canales y acceso a sistemas'),t('Staff ownership','Responsables del equipo'),t('Offer & memory permissions','Permisos de ofertas y memoria')],icon:ShieldCheck}, {title:t('Rehearse real stays','Ensayar estancias reales'),text:t('Test the questions, requests, offers and handoffs your guests actually make. Your team signs off before launch.','Prueba preguntas, solicitudes, ofertas y transferencias reales. Tu equipo aprueba antes del lanzamiento.'),items:[t('Guest questions','Preguntas del huésped'),t('Service exceptions','Excepciones del servicio'),t('Human handoffs','Transferencias al equipo')],icon:MessageCircle}, {title:t('Launch & measure','Lanzar y medir'),text:t('Start with a defined property and journey. Compare completed outcomes, review the evidence, then decide where to expand.','Empieza con un hotel y una experiencia definida. Compara resultados completados, revisa evidencia y decide dónde ampliar.'),items:[t('Defined pilot','Piloto definido'),t('Outcome comparison','Comparación de resultados'),t('Portfolio rollout decision','Decisión de expansión')],icon:LayoutDashboard}]
 const step=steps[active],Icon=step.icon
 return <div className="xp-setup"><div className="xp-setup-steps">{steps.map((s,i)=><button key={s.title} onClick={()=>setActive(i)} aria-pressed={active===i} type="button"><span>0{i+1}</span><strong>{s.title}</strong><ChevronRight size={16}/></button>)}</div><div className="xp-setup-scene" key={active}><div className="xp-setup-graphic" aria-hidden="true"><div className="xp-setup-center"><Icon size={30}/></div>{step.items.map((label,i)=><div className={`xp-setup-node xp-setup-node-${i}`} key={label}><Check size={14}/>{label}</div>)}<svg viewBox="0 0 500 260"><path d="M250 130 C200 130 175 50 110 50 M250 130 C300 130 335 55 385 55 M250 130 C250 170 250 200 250 220"/></svg></div><div className="xp-setup-description"><span className="xp-index">0{active+1} / 04</span><h3>{step.title}</h3><p>{step.text}</p><Link className="xp-inline-link" href="/implementation">{t('See the rollout plan','Ver el plan de implementación')}<ArrowRight size={16}/></Link></div></div></div>
}

export function ConnectionMap() {
 const t=useWords()
 const systems=[{name:t('Hotel knowledge','Conocimiento'),desc:t('Policies, rooms & services','Políticas y servicios'),icon:Globe2},{name:t('Hotel systems','Sistemas del hotel'),desc:t('PMS, dining & service tools','PMS y herramientas'),icon:LayoutDashboard},{name:t('Guest channels','Canales del huésped'),desc:t('Telephone, web & mobile','Teléfono, web y móvil'),icon:Phone},{name:t('Your people','Tu equipo'),desc:t('Requests & human handoffs','Solicitudes y transferencias'),icon:Users}]
 return <div className="xp-connections"><div className="xp-connection-center"><span className="xp-hc-symbol">h</span><strong>Hotel Companion</strong><span>{t('One guest experience','Una experiencia conectada')}</span></div><svg viewBox="0 0 1000 370" preserveAspectRatio="none" aria-hidden="true"><path d="M180 85 C400 85 390 185 500 185 M820 85 C600 85 610 185 500 185 M180 285 C400 285 390 185 500 185 M820 285 C600 285 610 185 500 185"/></svg>{systems.map((system,i)=>{const Icon=system.icon;return <div key={system.name} className={`xp-system xp-system-${i}`}><Icon size={20}/><strong>{system.name}</strong><span>{system.desc}</span></div>})}<small>{t('Connections and supported actions confirmed during setup. No stack replacement required.','Conexiones y acciones compatibles confirmadas durante la configuración. Sin reemplazar tu infraestructura.')}</small></div>
}

export function ValueExample() {
 const t=useWords(),id=useId(),[orders,setOrders]=useState(100)
 const sales=orders*60, costs=orders*20, baseline=orders*10,incremental=sales-costs-baseline
 const money=(value:number)=>`$${value.toLocaleString('en-US')}`
 return <div className="xp-value-example"><div className="xp-value-config"><Eyebrow>{t('ILLUSTRATIVE ECONOMICS · USD','EJEMPLO ECONÓMICO · USD')}</Eyebrow><h3>{t('Show the value.','Mostrar el valor.')}</h3><p>{t('An example using a $60 service, $20 delivery cost and $10 expected contribution without HC. Change the volume to explore the calculation.','Ejemplo con un servicio de $60, costo de $20 y contribución esperada sin HC de $10. Cambia el volumen para explorar el cálculo.')}</p><label htmlFor={id}>{t('Completed, paid orders','Pedidos completados y pagados')}<strong>{orders}</strong></label><input id={id} type="range" min="20" max="200" step="10" value={orders} onChange={e=>setOrders(Number(e.target.value))}/><small>{t('Not a forecast. Actual lift requires an agreed comparison.','No es un pronóstico. El incremento real requiere una comparación acordada.')}</small></div><div className="xp-value-calculation"><div><span>{t('Paid service revenue','Ingreso de servicios pagados')}</span><strong>{money(sales)}</strong></div><div><span>{t('Delivery costs','Costos de ejecución')}</span><strong>− {money(costs)}</strong></div><div><span>{t('Expected contribution without HC','Contribución esperada sin HC')}</span><strong>− {money(baseline)}</strong></div><div className="xp-value-total"><span>{t('Illustrative additional contribution','Contribución adicional ilustrativa')}</span><strong>{money(incremental)}</strong></div><div className="xp-value-bar" aria-hidden="true"><i/><i/><i/></div><p>{t('A success fee would be an agreed share of verified lift, after cancellations and refunds.','La comisión sería un porcentaje acordado del incremento verificado, tras cancelaciones y devoluciones.')}</p></div></div>
}

export function PilotClose() {
 const t=useWords()
 return <section className="xp-pilot" id="pilot"><div className="xp-wrap xp-pilot-grid"><div><Eyebrow>{t('START SMALL. PROVE THE VALUE.','EMPIEZA EN PEQUEÑO. DEMUESTRA EL VALOR.')}</Eyebrow><h2>{t('Let’s make your first','Que tu primer hotel')}<br/>{t('property the proof.','demuestre el valor.')}</h2></div><div><p>{t('Explore a qualified pilot with no upfront software or standard setup fee. Agree the journey, the measurement and our share of verified additional contribution before launch.','Explora un piloto elegible sin pago inicial de software ni configuración estándar. Acordamos la experiencia, la medición y nuestro porcentaje de la contribución adicional verificada antes de lanzar.')}</p><div className="xp-actions"><Action>{t('Discuss your pilot','Hablemos de tu piloto')}</Action><Action href="/implementation#pilot-terms" quiet>{t('Read the pilot approach','Ver condiciones del piloto')}</Action></div><small>{t('Eligibility and terms agreed first. Custom connections and optional tablet hardware scoped separately.','Elegibilidad y condiciones acordadas primero. Conexiones especiales y tablets opcionales cotizadas aparte.')}</small></div></div></section>
}

export function FeatureRows({ items }: { items: {title: string; body: string}[] }) {
 return <div className="xp-feature-rows">{items.map((item,i)=><article key={item.title}><span className="xp-index">0{i+1}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div>
}
export function Questions({ items }: { items: {q:string;a:string}[] }) {
 const t=useWords()
 return <section className="xp-section xp-wrap xp-faq"><SectionHeading eyebrow={t('A FEW PRACTICAL ANSWERS','RESPUESTAS PRÁCTICAS')} title={t('Before we begin.','Antes de empezar.')}/>{items.map(item=><details key={item.q}><summary>{item.q}<Plus size={17}/></summary><p>{item.a}</p></details>)}</section>
}
export function ContextFlow() {
 const t=useWords()
 const stages=[{icon:Phone,label:t('Before arrival','Antes de llegar'),detail:t('Quiet room. Anniversary.','Zona tranquila. Aniversario.')},{icon:Smartphone,label:t('During the stay','Durante la estancia'),detail:t('Vegetarian dinner. Extra towels.','Cena vegetariana. Toallas extra.')},{icon:Heart,label:t('On the next visit','En la próxima visita'),detail:t('Recognized preferences, with permission.','Preferencias reconocidas, con permiso.')}]
 return <div className="xp-context-flow">{stages.map((stage,i)=>{const Icon=stage.icon;return <div key={stage.label}><span className="xp-context-orb"><Icon size={25}/></span><small>0{i+1}</small><h3>{stage.label}</h3><p>{stage.detail}</p>{i<2&&<ArrowRight className="xp-context-arrow" size={24}/>}</div>})}<span className="xp-context-line" aria-hidden="true"/></div>
}
export function SurfaceExplorer() {
 const t=useWords(),[active,setActive]=useState(0)
 const surfaces=[{icon:Phone,label:t('Telephone','Teléfono'),scene:0,body:t('For callers asking about rooms, arrival and hotel services. Telephone routing, transfers and booking access are scoped for the property.','Para llamadas sobre habitaciones, llegadas y servicios. Rutas, transferencias y acceso a reservas definidos para cada hotel.')},{icon:Monitor,label:t('Desktop web','Web de escritorio'),scene:2,body:t('Give website visitors a conversation around your rooms, services and policies. Bring approved recommendations into the browsing experience.','Conversaciones sobre habitaciones, servicios y políticas. Recomendaciones aprobadas dentro de la experiencia de navegación.')},{icon:Smartphone,label:t('Mobile web','Web móvil'),scene:1,body:t('Guests open a link or scan a QR code. No guest app download. Voice, text and stay requests in an interface that travels with them.','Los huéspedes abren un enlace o escanean un QR. Sin descargar apps. Voz, texto y solicitudes en una interfaz que los acompaña.')},{icon:Tablet,label:t('In-room tablet','Tablet en habitación'),scene:3,body:t('A dedicated guest experience in the room, with hardware and installation tailored to your property. The companion remains the same across supported surfaces.','Una experiencia dedicada en la habitación, con dispositivos e instalación adaptados a tu hotel. El companion es el mismo en los canales compatibles.')}]
 const surface=surfaces[active]
 return <div className="xp-surface-explorer"><div className="xp-surface-select">{surfaces.map((s,i)=>{const Icon=s.icon;return <button onClick={()=>setActive(i)} aria-pressed={active===i} key={s.label} type="button"><Icon size={22}/><span>{s.label}</span><ChevronRight size={15}/></button>})}<p>{surface.body}</p><small>{t('WhatsApp can be assessed as an additional channel during setup.','WhatsApp puede evaluarse como canal adicional durante la configuración.')}</small></div><GuestScene index={surface.scene} compact/></div>
}
