'use client'

import Image from 'next/image'
import { useId, type ReactNode } from 'react'
import { Check, Heart, Mic, Phone, ShieldCheck, Smartphone, Tablet, Monitor } from 'lucide-react'
import { useLang } from '@/lib/i18n/LanguageContext'
import { Action, Eyebrow, Tabs, useWords } from './Experience'
import { ProductCapture } from './ProductCapture'
import { Sequence, SequenceControls, SequenceRail, SequenceTabs, useSequence } from './Sequence'
import { ValueScene } from './ValueScene'
import { ConversationThread } from './ConversationThread'
import { conversationStory } from './conversation-stories'

export function PageIntro({eyebrow,title,accent,body}:{eyebrow:string;title:string;accent?:string;body:string}) {
 return <header className="hc-page-intro xp-wrap"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}{accent&&<><br/><span>{accent}</span></>}</h1><p>{body}</p></header>
}

export function Chapter({id,eyebrow,title,body,children,tint=false}:{id?:string;eyebrow:string;title:string;body?:string;children:ReactNode;tint?:boolean}) {
 return <section id={id} className={`hc-chapter ${tint?'hc-chapter-tint':''}`}><div className="xp-wrap"><div className="hc-chapter-heading"><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{body&&<p>{body}</p>}</div>{children}</div></section>
}

export function Details({items}:{items:{q:string;a:string}[]}) {
 return <div className="hc-page-details">{items.map(({q,a})=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div>
}

export function PhotoStory({image,alt,title,body,children}:{image:string;alt:string;title:string;body:string;children?:ReactNode}) {
 return <div className="hc-photo-story" data-motion-scene><div className="hc-story-image" data-motion-beat><Image src={image} alt={alt} width={900} height={900} sizes="(max-width:800px) 92vw, 50vw"/></div><div className="hc-story-copy" data-motion-beat><h3>{title}</h3><p>{body}</p>{children}</div></div>
}

export function MemoryPanel() {
 const t=useWords(), playback=useSequence(3,8000)
 const moments=[{image:'/assets/ui/suite-1.webp',title:t('Before arrival','Antes de llegar'),note:t('“A quiet room, please.”','«Una habitación tranquila».')},{image:'/assets/ui/dish-1.webp',title:t('During the stay','Durante la estancia'),note:t('“Dinner somewhere peaceful.”','«Una cena en un lugar tranquilo».')},{image:'/assets/ui/suite-garden.webp',title:t('On the next visit','En la próxima visita'),note:t('“Welcome back. Another quiet room?”','«Bienvenido de nuevo. ¿Otra habitación tranquila?»')}]
 return <Sequence playback={playback} className="hc-memory-story"><div className="hc-phone-step-nav"><SequenceTabs labels={moments.map(m=>m.title)} active={playback.active} onChange={playback.select} name="memory-phone" playback={playback}/></div><SequenceControls playback={playback}/><div className="hc-memory-profile"><span className="hc-memory-avatar">JL</span><div><strong>Jamie L.</strong><span>{t('Shared preference','Preferencia compartida')}</span></div><p><Heart size={15}/>{t('Quiet surroundings','Entorno tranquilo')}</p><small><ShieldCheck size={13}/>{t('Saved with guest permission','Guardada con permiso del huésped')}</small></div><ol className="hc-memory-moments">{moments.map((m,i)=><li key={m.title} data-active={playback.active===i} id={playback.active===i?"memory-phone-panel":undefined} aria-labelledby={playback.active===i?`memory-phone-tab-${i}`:undefined}><button type="button" className="hc-memory-step" aria-label={m.title} aria-pressed={playback.active===i} onClick={()=>playback.select(i)}><span>0{i+1}</span><SequenceRail active={playback.active===i}/></button><Image src={m.image} alt="" width={500} height={320} sizes="(max-width:800px) 85vw, 280px"/><h3>{m.title}</h3><p>{m.note}</p></li>)}</ol><small className="hc-visual-caption">{t('Illustrative guest journey','Recorrido ilustrativo del huésped')}</small></Sequence>
}

export function ChannelStage() {
 const t=useWords(),{lang}=useLang(),playback=useSequence(4,18000,0,true),active=playback.active,setActive=playback.select
 const channels=[
  {label:t('Telephone','Teléfono'),icon:Phone,title:t('Answer the call. Keep the context.','Responde la llamada. Conserva el contexto.'),body:t('Natural voice conversations for questions, recommendations and supported requests. Routing and transfers are scoped for your hotel.','Conversaciones naturales para preguntas, recomendaciones y solicitudes compatibles. Rutas y transferencias definidas para tu hotel.'),view:'home'},
  {label:t('Desktop web','Web de escritorio'),icon:Monitor,title:t('Your hotel, ready to explore.','Tu hotel, listo para explorar.'),body:t('Help website visitors discover rooms and services through conversation and visual options.','Ayuda a descubrir habitaciones y servicios con conversación y opciones visuales.'),view:'rooms'},
  {label:t('Mobile web','Web móvil'),icon:Smartphone,title:t('A link. A QR code. A conversation.','Un enlace. Un QR. Una conversación.'),body:t('Guests open HC on their own phone. No app download needed.','El huésped abre HC en su teléfono. Sin descargar una app.'),view:'home'},
  {label:t('In-Room Tablets','Tablets en la habitación'),icon:Tablet,title:t('Hotel service, right in the room.','Los servicios del hotel, en la habitación.'),body:t('A dedicated guest screen that brings your hotel’s services and recommendations into the room.','Una pantalla dedicada que acerca los servicios y recomendaciones de tu hotel al huésped.'),view:'dining'},
 ]
 const item=channels[active],Icon=item.icon
 return <Sequence playback={playback} className="hc-channel-stage"><Tabs labels={channels.map(c=>c.label)} active={active} onChange={setActive} name="guest-channels" playback={playback}/><div key={active} id="guest-channels-panel" role="tabpanel" aria-labelledby={`guest-channels-tab-${active}`}><div className="hc-channel-copy"><Icon size={24}/><h3>{item.title}</h3><p>{item.body}</p></div>{active===0?<div className="hc-phone-scene"><span className="hc-phone-symbol"><Phone size={30}/></span><p>{t('Incoming guest call','Llamada de un huésped')}</p><div className="hc-call-wave" aria-hidden="true">{[12,23,37,26,45,19,34,48,22,38,28,15,36,46,24,12].map((h,i)=><i key={i} style={{height:h}}/>)}</div><span><Mic size={15}/> Hotel Companion</span><ValueScene index={0} kind="channel"/><small>{t('Illustrative voice interaction','Interacción de voz ilustrativa')}</small></div>:<div className={active===2?'hc-channel-device':'hc-channel-preview'}><div className={`hc-channel-screen ${active===2?'hc-channel-mobile':''}`}>{active===2?<Image src={`/assets/experience/sales-phone-home${lang==='es'?'-es':''}.webp`} width={390} height={844} alt={t('Hotel Companion on a guest’s phone','Hotel Companion en el teléfono del huésped')} sizes="(max-width:700px) 90vw, 210px"/>:<ProductCapture view={item.view} lang={lang} alt={t('Hotel Companion guest interface','Interfaz del huésped de Hotel Companion')}/>}</div><ValueScene index={active} kind="channel"/></div>}</div></Sequence>
}

export function RecoveryStory() {
 const t=useWords(),{lang}=useLang(),playback=useSequence(4,18000,0,true),active=playback.active,setActive=playback.select
 const name=`recovery-${useId().replace(/:/g,'')}`
 const examples=[
  {label:t('Room features','Detalles de la habitación'),ask:t('“A balcony for our morning coffee?”','«¿Un balcón para tomar café por la mañana?»'),reply:t('Explore a garden-facing room with a private balcony. Check the upgrade price and availability for your dates.','Descubre una habitación con balcón privado hacia el jardín. Consulta el precio de la mejora y la disponibilidad para tus fechas.'),offer:t('Your own balcony. A better morning.','Tu propio balcón. Una mejor mañana.'),image:'/assets/ui/suite-garden.webp',tag:t('Matched to the feature the guest wants','El detalle que busca el huésped')},
  {label:t('Limited time','Poco tiempo'),ask:t('“We only have an hour.”','«Solo tenemos una hora».') ,reply:t('A shorter treatment that fits your afternoon.','Un tratamiento más corto que encaja con tu tarde.'),offer:t('45-minute spa treatment','Tratamiento de spa de 45 minutos'),image:'/assets/ui/spa-1.webp',tag:t('Fits the available time','Encaja con el tiempo disponible')},
  {label:t('Budget mismatch','Otro presupuesto'),ask:t('“Something simpler for dinner?”','«¿Algo más sencillo para cenar?»'),reply:t('An à la carte dinner instead of the tasting menu.','Una cena a la carta en lugar del menú degustación.'),offer:t('Dinner at your own pace','Cena a tu ritmo'),image:'/assets/ui/dish-2.webp',tag:t('An approved alternative','Una alternativa aprobada')},
  {label:t('First choice unavailable','Primera opción no disponible'),ask:t('“Is there a table at 8?”','«¿Hay mesa a las ocho?»'),reply:t('That time is full. Shall we check a later sitting?','Ese horario está lleno. ¿Revisamos un turno más tarde?'),offer:t('A different dinner time','Otro horario para cenar'),image:'/assets/ui/dish-1.webp',tag:t('Check the next available option','Consultar la siguiente opción disponible')},
 ]
 const item=examples[active], story=conversationStory('recovery',active,lang)
 return <Sequence playback={playback} className="hc-recovery"><Tabs labels={examples.map(e=>e.label)} active={active} onChange={setActive} name={name} playback={playback}/><div key={active} className="hc-recovery-scene" id={`${name}-panel`} role="tabpanel" aria-labelledby={`${name}-tab-${active}`}><div className="hc-recovery-conversation"><ConversationThread messages={story.messages} outcome={story.outcome}/></div><div className="hc-recovered-offer"><Image src={item.image} alt={item.offer} width={700} height={440} sizes="(max-width:800px) 90vw, 500px"/><div><small><Check size={13}/>{item.tag}</small><h3>{item.offer}</h3></div></div></div><small className="hc-visual-caption">{t('Illustrative scenarios. Offers require approved prices, availability and confirmation.','Escenarios ilustrativos. Las ofertas requieren precios aprobados, disponibilidad y confirmación.')}</small></Sequence>
}

export function ContributionExample() {
 const t=useWords()
 return <div className="hc-contribution"><div className="hc-contribution-numbers" data-motion-scene>{[[t('Paid sales assisted by HC','Ventas pagadas asistidas por HC'),'$6,000'],[t('Delivery costs','Costos del servicio'),'− $2,000'],[t('Expected contribution without HC','Contribución esperada sin HC'),'− $1,000'],[t('Additional contribution','Contribución adicional'),'$3,000']].map(([label,value],i)=><div key={label} data-motion-beat data-total={i===3}><strong>{value}</strong><span>{label}</span></div>)}</div><small>{t('Illustrative USD example. Not a result or forecast.','Ejemplo ilustrativo en USD. No es un resultado ni un pronóstico.')}</small><Details items={[{q:t('How do we establish what would happen without HC?','¿Cómo estimamos lo que ocurriría sin HC?'),a:t('Before launch, agree the eligible guest journey, source records, costs and comparison. Where practical, compare an HC group with a concurrent control group using the same outcome definitions. A historical comparison needs adjustments for occupancy, seasonality, prices and other promotions and provides weaker evidence. The hotel reviews the reconciled records and agreed calculation; tracked sales alone do not establish lift.','Antes de lanzar se acuerdan experiencia, registros, costos y comparación. Cuando sea viable, se compara un grupo HC con un grupo de control simultáneo usando las mismas definiciones. Una comparación histórica requiere ajustes por ocupación, temporada, precios y promociones, y aporta evidencia más débil. El hotel revisa registros y cálculo; registrar ventas no demuestra incremento.')},{q:t('How is additional contribution calculated?','¿Cómo se calcula la contribución adicional?'),a:t('This example uses 100 completed $60 orders, $20 delivery cost per order and $10 expected contribution without HC: $6,000 − $2,000 − $1,000 = $3,000. A real pilot needs an agreed comparison and reconciled transactions, discounts, refunds, commissions and redeemed benefits. Assisted sales are reported separately from estimated incrementality.','Este ejemplo usa 100 pedidos completados de $60, costo de $20 por pedido y contribución esperada sin HC de $10: $6,000 − $2,000 − $1,000 = $3,000. Un piloto real requiere comparación acordada y conciliación de transacciones, descuentos, devoluciones, comisiones y beneficios usados. Las ventas asistidas se separan del incremento estimado.')} ]}/></div>
}

export function PilotTerms() {
 const t=useWords()
 return <div className="hc-pilot-summary" id="pilot-terms"><span className="hc-pilot-zero">$0<small>{t('upfront software + standard setup','software + configuración estándar iniciales')}</small></span><div><h3>{t('A qualified, scoped pilot.','Un piloto elegible y definido.')}</h3><p>{t('One hotel. A defined guest journey. A success fee on verified additional contribution.','Un hotel. Una experiencia definida. Comisión sobre contribución adicional verificada.')}</p><Action>{t('Discuss eligibility','Hablemos de elegibilidad')}</Action></div><Details items={[
 {q:t('Which hotels qualify for the pilot?','¿Qué hoteles son elegibles para el piloto?'),a:t('We assess three things together: a guest journey with eligible services to offer, an accountable team able to confirm and fulfil them, and access to the systems and outcome records needed for measurement. The agreed pilot must be small enough to launch and measurable enough to evaluate. Scope and any custom work are confirmed before a commitment.','Revisamos tres cosas: una experiencia con servicios elegibles, un equipo que pueda confirmar y cumplir, y acceso a sistemas y registros para medir. El piloto debe ser acotado para lanzar y medible para evaluar. Alcance y trabajo especial se confirman antes de comprometerse.')},
 {q:t('What does the hotel provide?','¿Qué aporta el hotel?'),a:t('An accountable hotel champion, approved knowledge and offers, department owners, required system access and records to reconcile completed outcomes. We agree channels, supported actions, handoffs, identity and retention before launch.','Un responsable del hotel, conocimiento y ofertas aprobados, responsables por área, acceso a sistemas y registros para conciliar resultados. Acordamos canales, acciones, transferencias, identidad y retención antes de lanzar.')},
 {q:t('What do we pay, and what counts?','¿Qué pagamos y qué cuenta?'),a:t('The proposed pilot has no upfront software or standard setup fee for the agreed eligible scope. The fee is an agreed share of verified additional contribution after the agreed costs, cancellations and refunds. No verified lift means no success fee. Custom connections and optional tablet hardware/setup are priced separately. Duration, comparison method and fees are agreed before launch.','El piloto propuesto no tiene pago inicial de software ni configuración estándar para el alcance elegible acordado. La comisión es un porcentaje de la contribución adicional verificada tras costos, cancelaciones y devoluciones acordados. Sin incremento verificado, no hay comisión de éxito. Conexiones especiales y hardware/configuración de tablets se cotizan aparte. Duración, comparación y comisiones se acuerdan antes de lanzar.')},
 {q:t('How long does it run, and can we stop?','¿Cuánto dura y podemos detenerlo?'),a:t('The written pilot plan sets the launch criteria, measurement period, review dates, success-fee percentage and stop conditions. Agree how pending requests, guest communication, access removal and the final reconciliation are handled on exit. A pilot does not automatically commit the hotel to a portfolio rollout.','El plan escrito define criterios de lanzamiento, período de medición, revisiones, porcentaje y condiciones de salida. Se acuerdan solicitudes pendientes, comunicación, retiro de accesos y conciliación final. El piloto no compromete automáticamente a ampliar al portafolio.')},
 {q:t('How is the success fee calculated?','¿Cómo se calcula la comisión de éxito?'),a:t('Agreed percentage × positive verified additional contribution for the eligible pilot scope, after the agreed costs and reconciliation. Assisted gross revenue is not the fee base. If the agreed method establishes no positive lift, no success fee is due. The hotel and HC review the calculation together before billing.','Porcentaje acordado × contribución adicional positiva verificada para el alcance elegible, tras costos y conciliación. El ingreso bruto asistido no es la base. Si el método no establece incremento positivo, no hay comisión. Hotel y HC revisan el cálculo antes de facturar.')},
 {q:t('What earns a portfolio rollout?','¿Qué justifica ampliar al portafolio?'),a:t('Evidence that the guest journey works for guests and staff, together with verified additional contribution under the agreed method. Expansion includes a separately agreed implementation fee, connection plan and property-specific responsibilities.','Evidencia de una experiencia útil para huéspedes y equipo, junto con contribución adicional verificada según el método acordado. La expansión incluye costo de implementación, plan de conexiones y responsabilidades por hotel acordados por separado.')},
 ]}/></div>
}
